// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: LexerFormsConfig.jflex

/********************** paquetes y otros ***********************/
package com.pablocompany.proyectono1_compi1.compiler.logic.formulario;

/*P*/

import java_cup.runtime.*;
import java.util.*;

/*Mis imports*/
import com.pablocompany.proyectono1_compi1.compiler.models.errores.ErrorAnalisis;


@SuppressWarnings("fallthrough")
public class LexerForms implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\2\u1f00\1\u2000\6\u1f00\1\u2100\1\u2200\1\u2300"+
    "\1\u2400\1\u2500\1\u2600\1\u2700\1\u2800\1\u1f00\31\u0100\1\u2900"+
    "\121\u0100\1\u2a00\4\u0100\1\u2b00\1\u0100\1\u2c00\1\u2d00\1\u2e00"+
    "\1\u2f00\1\u3000\1\u3100\53\u0100\1\u3200\10\u3300\31\u3400\1\u0100"+
    "\1\u3500\1\u3600\1\u0100\1\u3700\1\u3800\1\u3900\1\u3a00\1\u3b00"+
    "\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u0100\1\u4000\1\u4100\1\u4200"+
    "\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900\1\u4a00"+
    "\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u5000\1\u5100\1\u5200"+
    "\1\u5300\1\u3400\1\u5400\1\u5500\1\u5600\1\u5700\3\u0100\1\u5800"+
    "\1\u5900\1\u5a00\11\u3400\1\u5b00\4\u0100\1\u5c00\17\u3400\2\u0100"+
    "\1\u5d00\41\u3400\2\u0100\1\u5e00\1\u5f00\2\u3400\1\u6000\1\u6100"+
    "\27\u0100\1\u6200\2\u0100\1\u6300\1\u6400\1\u6500\1\u6600\41\u3400"+
    "\1\u6700\1\u0100\1\u6800\1\u6900\11\u3400\1\u6a00\22\u3400\1\u6b00"+
    "\1\u6c00\1\u6d00\1\u6e00\1\u6f00\1\u7000\1\u7100\1\u7200\1\u7300"+
    "\2\u1f00\1\u7400\4\u3400\1\u7500\1\u7600\1\u7700\1\u7800\1\u3400"+
    "\1\u7900\2\u3400\1\u7a00\1\u7b00\1\u7c00\2\u3400\1\u7d00\1\u7e00"+
    "\1\u7f00\1\u3400\1\u8000\1\u8100\1\u8200\3\u1f00\1\u8300\1\u8400"+
    "\1\u8500\1\u8600\1\u8700\1\u8800\4\u3400\246\u0100\1\u8900\20\u0100"+
    "\1\u8a00\1\u8b00\25\u0100\1\u8c00\34\u0100\1\u8d00\14\u3400\2\u0100"+
    "\1\u8e00\5\u3400\23\u6400\1\u8f00\17\u6400\1\u9000\u0adc\u3400\1\u9100"+
    "\1\u9200\u02fe\u3400";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\16\0\4\6"+
    "\1\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\3\26\1\27\6\26\1\30\1\15\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\47\1\52"+
    "\1\53\1\54\1\47\1\55\1\56\1\57\1\60\1\47"+
    "\1\61\1\47\1\62\1\47\1\63\1\64\1\65\1\66"+
    "\1\47\1\15\1\67\1\70\1\71\1\72\1\73\1\43"+
    "\1\74\1\75\1\76\2\47\1\77\1\100\1\101\1\102"+
    "\1\103\1\47\1\104\1\105\1\106\1\107\5\47\1\15"+
    "\1\110\1\15\1\111\6\0\1\112\32\0\2\15\4\47"+
    "\4\15\1\47\2\15\1\0\7\15\1\47\4\15\1\47"+
    "\5\15\27\47\1\15\37\47\1\15\u01ca\47\4\15\14\47"+
    "\16\15\5\47\7\15\1\47\1\15\1\47\21\15\160\113"+
    "\5\47\1\15\2\47\2\6\4\47\1\15\1\47\4\6"+
    "\2\15\1\47\1\15\3\47\1\6\1\47\1\6\24\47"+
    "\1\6\123\47\1\15\213\47\1\15\5\113\2\15\246\47"+
    "\1\6\46\47\2\6\1\47\6\15\51\47\2\15\2\6"+
    "\2\15\1\47\1\6\55\113\1\15\1\113\1\15\2\113"+
    "\1\15\2\113\1\15\1\113\10\6\33\47\4\6\4\47"+
    "\2\15\13\6\6\0\5\15\1\47\4\15\13\113\1\15"+
    "\1\0\1\6\2\15\53\47\37\113\4\15\2\47\1\113"+
    "\143\47\1\15\1\47\7\113\1\0\1\15\6\113\2\47"+
    "\2\113\1\15\4\113\2\47\12\113\3\47\2\15\1\47"+
    "\16\15\1\6\1\0\1\47\1\113\36\47\33\113\2\6"+
    "\131\47\13\113\1\47\16\6\12\113\41\47\11\113\2\47"+
    "\4\15\1\47\2\6\1\113\30\47\4\113\1\47\11\113"+
    "\1\47\3\113\1\47\5\113\2\6\17\15\1\6\31\47"+
    "\3\113\2\6\1\15\1\6\13\47\5\6\30\114\1\6"+
    "\6\114\1\6\2\0\6\6\10\0\25\47\1\114\10\47"+
    "\14\114\11\0\17\113\1\0\41\113\66\47\3\113\1\47"+
    "\22\113\1\47\7\113\12\47\2\113\2\15\12\113\1\15"+
    "\20\47\3\113\1\6\10\47\2\6\2\47\2\6\26\47"+
    "\1\6\7\47\1\6\1\47\3\6\4\47\2\6\1\113"+
    "\1\47\7\113\2\6\2\113\2\6\3\113\1\47\10\6"+
    "\1\113\4\6\2\47\1\6\3\47\2\113\2\6\12\113"+
    "\4\47\7\15\2\47\1\15\1\113\2\6\3\113\1\6"+
    "\6\47\4\6\2\47\2\6\26\47\1\6\7\47\1\6"+
    "\2\47\1\6\2\47\1\6\2\47\2\6\1\113\1\6"+
    "\5\113\4\6\2\113\2\6\3\113\3\6\1\113\7\6"+
    "\4\47\1\6\1\47\7\6\14\113\3\47\1\113\1\15"+
    "\12\6\3\113\1\6\11\47\1\6\3\47\1\6\26\47"+
    "\1\6\7\47\1\6\2\47\1\6\5\47\2\6\1\113"+
    "\1\47\10\113\1\6\3\113\1\6\3\113\2\6\1\47"+
    "\17\6\2\47\2\113\2\6\12\113\1\15\1\47\7\6"+
    "\1\47\6\113\1\6\3\113\1\6\10\47\2\6\2\47"+
    "\2\6\26\47\1\6\7\47\1\6\2\47\1\6\5\47"+
    "\2\6\1\113\1\47\7\113\2\6\2\113\2\6\3\113"+
    "\7\6\1\0\2\113\4\6\2\47\1\6\3\47\2\113"+
    "\2\6\12\113\1\15\1\47\6\15\12\6\1\113\1\47"+
    "\1\6\6\47\3\6\3\47\1\6\4\47\3\6\2\47"+
    "\1\6\1\47\1\6\2\47\3\6\2\47\3\6\3\47"+
    "\3\6\14\47\4\6\5\113\3\6\3\113\1\6\4\113"+
    "\2\6\1\47\6\6\1\113\16\6\12\113\11\15\1\47"+
    "\1\15\5\6\5\113\10\47\1\6\3\47\1\6\27\47"+
    "\1\6\20\47\2\6\1\0\1\47\7\113\1\6\3\113"+
    "\1\6\4\113\7\6\2\113\1\6\3\47\2\6\1\114"+
    "\2\6\2\47\2\113\2\6\12\113\7\6\11\15\1\47"+
    "\3\113\1\15\10\47\1\6\3\47\1\6\27\47\1\6"+
    "\12\47\1\6\5\47\2\6\1\113\1\47\7\113\1\6"+
    "\3\113\1\6\4\113\7\6\2\113\6\6\1\114\1\47"+
    "\1\6\2\47\2\113\2\6\12\113\1\6\2\47\1\0"+
    "\14\6\4\113\1\114\10\47\1\6\3\47\1\6\51\47"+
    "\2\113\1\47\7\113\1\6\3\113\1\6\4\113\1\47"+
    "\1\15\4\6\3\47\1\113\7\15\3\47\2\113\2\6"+
    "\12\113\12\15\6\47\1\6\1\0\2\113\1\6\22\47"+
    "\3\6\30\47\1\6\11\47\1\6\1\47\2\6\7\47"+
    "\3\6\1\113\4\6\6\113\1\6\1\113\1\6\10\113"+
    "\6\6\12\113\2\6\2\113\1\15\14\6\60\47\1\113"+
    "\2\47\7\113\4\6\10\47\10\113\1\15\12\113\2\15"+
    "\45\6\2\47\1\6\1\47\1\6\5\47\1\6\30\47"+
    "\1\6\1\47\1\6\12\47\1\113\2\47\11\113\1\47"+
    "\2\6\5\47\1\6\1\47\1\6\6\113\1\0\1\6"+
    "\12\113\2\6\4\47\40\6\1\47\27\15\2\113\6\15"+
    "\12\113\13\15\1\113\1\15\1\113\1\15\1\113\4\15"+
    "\2\113\10\47\1\6\44\47\4\6\24\113\1\15\2\113"+
    "\5\47\13\113\1\6\44\113\1\6\10\15\1\113\6\15"+
    "\1\6\15\15\45\6\53\47\24\113\1\47\12\113\6\15"+
    "\6\47\4\113\4\47\3\113\1\47\3\113\2\47\7\113"+
    "\3\47\4\113\15\47\14\113\1\47\17\113\2\15\46\47"+
    "\1\6\1\47\5\6\1\47\2\6\53\47\1\15\115\47"+
    "\1\6\4\47\2\6\7\47\1\6\1\47\1\6\4\47"+
    "\2\6\51\47\1\6\4\47\2\6\41\47\1\6\4\47"+
    "\2\6\7\47\1\6\1\47\1\6\4\47\2\6\17\47"+
    "\1\6\71\47\1\6\4\47\2\6\103\47\2\6\3\113"+
    "\35\15\3\6\20\47\12\15\6\6\126\47\2\6\6\47"+
    "\2\6\1\15\u016c\47\2\15\21\47\1\15\32\47\2\15"+
    "\3\6\113\47\3\15\13\47\7\6\15\47\1\114\4\47"+
    "\3\113\1\0\11\6\1\114\22\47\3\113\2\15\11\6"+
    "\22\47\2\113\14\6\15\47\1\6\3\47\1\6\2\113"+
    "\14\6\64\47\40\113\3\15\1\47\3\15\2\47\1\113"+
    "\2\6\12\113\6\6\12\15\6\6\13\15\3\113\2\0"+
    "\12\113\6\6\131\47\7\6\5\47\2\113\42\47\1\113"+
    "\1\47\5\6\106\47\12\6\37\47\1\6\14\113\4\6"+
    "\14\113\4\6\1\15\3\6\2\15\12\113\36\47\2\6"+
    "\5\47\13\6\54\47\4\6\32\47\6\6\12\113\1\15"+
    "\3\6\42\15\27\47\5\113\2\6\2\15\65\47\12\113"+
    "\1\6\35\113\2\6\13\113\6\6\12\113\6\6\7\15"+
    "\1\47\6\15\2\6\16\113\1\15\20\0\61\6\5\113"+
    "\57\47\21\113\7\47\1\114\3\6\12\113\21\15\11\113"+
    "\11\15\3\6\3\113\36\47\15\113\2\47\12\113\54\47"+
    "\16\113\10\6\4\15\44\47\24\113\3\6\5\15\12\113"+
    "\3\6\3\47\12\113\44\47\2\15\11\47\7\6\53\47"+
    "\2\6\3\47\10\15\10\6\3\113\1\15\25\113\4\47"+
    "\1\113\6\47\1\113\2\47\3\113\1\47\5\6\300\47"+
    "\72\113\1\0\5\113\26\47\2\6\6\47\2\6\46\47"+
    "\2\6\6\47\2\6\10\47\1\6\1\47\1\6\1\47"+
    "\1\6\1\47\1\6\37\47\2\6\65\47\1\6\7\47"+
    "\1\15\1\47\3\15\3\47\1\6\7\47\3\15\4\47"+
    "\2\6\6\47\1\6\3\15\15\47\3\15\2\6\3\47"+
    "\1\6\7\47\2\15\1\6\13\15\5\0\30\15\2\115"+
    "\5\0\20\15\2\47\23\15\1\47\13\15\5\0\1\6"+
    "\12\0\1\15\1\47\2\6\13\15\1\47\17\15\1\6"+
    "\15\47\3\6\40\47\1\114\17\6\15\113\4\15\1\113"+
    "\3\15\14\113\17\6\2\15\1\47\4\15\1\47\2\15"+
    "\12\47\1\15\1\47\3\15\5\47\6\15\1\47\1\15"+
    "\1\47\1\15\1\47\1\15\4\47\1\15\13\47\2\15"+
    "\4\47\5\15\5\47\4\15\1\47\21\15\51\47\3\15"+
    "\4\6\u0197\15\31\6\13\15\25\6\u0114\15\2\6\40\15"+
    "\2\6\150\15\57\47\1\114\57\47\1\114\205\47\6\15"+
    "\4\47\3\113\2\47\5\6\7\15\46\47\1\6\1\47"+
    "\5\6\1\47\2\6\70\47\7\6\1\47\1\15\16\6"+
    "\1\113\27\47\11\6\7\47\1\6\7\47\1\6\7\47"+
    "\1\6\7\47\1\6\7\47\1\6\7\47\1\6\7\47"+
    "\1\6\7\47\1\6\40\113\57\15\1\47\40\15\60\6"+
    "\32\15\1\6\131\15\14\6\326\15\32\6\14\15\4\6"+
    "\5\15\3\47\31\15\11\47\6\113\1\15\5\47\2\15"+
    "\5\47\3\15\1\6\126\47\2\6\2\113\2\15\3\47"+
    "\1\15\132\47\1\15\4\47\5\6\53\47\1\6\136\47"+
    "\1\6\20\15\33\47\5\114\44\15\14\6\20\47\37\15"+
    "\1\6\340\15\266\47\12\114\100\15\360\47\20\114\215\47"+
    "\3\6\67\15\11\6\56\47\2\15\15\47\3\15\20\47"+
    "\12\113\2\47\24\6\57\47\1\113\4\15\12\113\1\15"+
    "\37\47\2\113\120\47\2\113\6\15\10\6\27\15\11\47"+
    "\2\15\147\47\2\15\65\47\2\114\5\47\4\114\5\6"+
    "\2\114\1\6\1\114\1\6\5\114\30\6\5\114\13\47"+
    "\1\113\3\47\1\113\4\47\1\113\27\47\5\113\4\15"+
    "\1\0\3\6\10\15\1\47\1\15\6\6\64\47\4\15"+
    "\10\6\2\113\62\47\22\113\10\6\2\15\12\113\6\6"+
    "\22\113\6\47\3\15\1\47\1\15\2\47\13\113\34\47"+
    "\10\113\2\15\27\47\15\113\13\6\1\15\35\47\3\6"+
    "\4\113\57\47\16\113\15\15\1\6\1\47\12\113\4\6"+
    "\2\15\5\47\1\113\12\47\12\113\5\47\1\6\51\47"+
    "\16\113\11\6\3\47\1\113\10\47\2\113\2\6\12\113"+
    "\2\6\4\15\27\47\3\15\1\47\3\113\62\47\1\113"+
    "\1\47\3\113\2\47\2\113\5\47\2\113\1\47\1\113"+
    "\1\47\30\6\3\47\2\15\13\47\5\113\2\15\3\47"+
    "\2\113\12\6\6\47\2\6\6\47\2\6\6\47\11\6"+
    "\7\47\1\6\7\47\1\6\53\47\1\15\14\47\2\114"+
    "\6\6\163\47\10\113\1\15\2\113\2\6\12\113\6\6"+
    "\244\47\14\6\27\47\4\6\61\47\4\6\u0100\115\u0100\6"+
    "\156\47\2\6\152\47\46\6\7\47\14\6\5\47\5\6"+
    "\1\47\1\113\12\47\1\15\15\47\1\6\5\47\1\6"+
    "\1\47\1\6\2\47\1\6\2\47\1\6\154\47\20\15"+
    "\21\6\153\47\2\15\20\6\100\47\2\6\66\47\50\6"+
    "\15\47\1\15\2\6\20\113\12\15\6\6\20\113\3\15"+
    "\2\47\30\15\3\47\3\15\1\6\23\15\1\6\1\15"+
    "\1\47\2\15\4\6\5\47\1\6\207\47\2\6\1\0"+
    "\1\6\3\15\1\47\13\15\12\113\7\15\32\47\4\15"+
    "\1\47\1\15\32\47\13\15\131\47\3\6\6\47\2\6"+
    "\6\47\2\6\6\47\2\6\3\47\3\6\2\47\3\15"+
    "\2\47\1\6\7\15\12\6\3\0\2\15\2\6\14\47"+
    "\1\6\32\47\1\6\23\47\1\6\2\47\1\6\17\47"+
    "\2\6\16\47\42\6\173\47\5\6\3\15\4\6\55\15"+
    "\3\6\11\15\65\47\32\15\1\6\14\15\4\6\1\15"+
    "\57\6\55\15\1\113\202\6\35\47\3\6\61\47\17\6"+
    "\1\113\33\15\4\6\40\47\4\15\11\6\36\47\5\6"+
    "\46\47\5\113\5\6\36\47\1\6\1\15\44\47\4\6"+
    "\10\47\1\15\5\47\52\6\236\47\2\6\12\113\6\6"+
    "\44\47\4\6\44\47\4\6\50\47\10\6\64\47\13\6"+
    "\1\15\13\114\1\6\17\114\1\6\7\114\1\6\2\114"+
    "\1\6\13\114\1\6\17\114\1\6\7\114\1\6\2\114"+
    "\103\6\67\47\11\6\26\47\12\6\10\47\30\6\6\114"+
    "\1\6\52\114\1\6\11\114\105\6\6\47\2\6\1\47"+
    "\1\6\54\47\1\6\2\47\3\6\1\47\2\6\27\47"+
    "\1\6\11\15\27\47\11\15\37\47\10\6\11\15\60\6"+
    "\23\47\1\6\2\47\5\6\5\15\26\47\6\15\3\6"+
    "\1\15\32\47\5\6\1\15\100\6\70\47\4\6\2\15"+
    "\2\47\20\15\2\6\56\15\1\47\3\113\1\6\2\113"+
    "\5\6\4\113\4\47\1\6\3\47\1\6\35\47\2\6"+
    "\3\113\4\6\1\113\11\15\7\6\11\15\7\6\35\47"+
    "\3\15\35\47\3\15\40\6\10\47\1\15\34\47\2\113"+
    "\4\6\14\15\11\6\66\47\3\6\7\15\26\47\2\6"+
    "\10\15\23\47\5\6\10\15\22\47\7\6\4\15\14\6"+
    "\7\15\120\6\111\47\67\6\63\47\15\6\63\47\7\6"+
    "\6\15\44\47\4\113\10\6\12\113\u0126\6\37\15\1\6"+
    "\52\114\1\6\2\0\3\6\2\114\113\6\3\0\35\47"+
    "\12\15\1\47\10\6\26\47\13\113\11\15\26\6\22\114"+
    "\4\0\52\6\25\114\33\6\27\47\11\6\3\113\65\47"+
    "\17\113\7\15\4\6\24\15\12\113\1\0\2\114\2\0"+
    "\1\114\11\6\4\113\55\47\13\113\2\15\1\0\4\15"+
    "\1\0\12\6\1\0\2\6\31\47\7\6\12\113\6\6"+
    "\3\113\44\47\16\113\1\6\12\113\4\15\1\47\2\113"+
    "\1\114\10\6\43\47\1\113\2\15\1\47\11\6\3\113"+
    "\60\47\16\113\4\47\4\15\4\113\1\15\2\0\12\113"+
    "\1\47\1\15\1\47\3\15\1\6\24\15\13\6\22\47"+
    "\1\6\31\47\14\113\6\15\1\113\2\114\1\0\76\6"+
    "\7\47\1\6\1\47\1\6\4\47\1\6\17\47\1\6"+
    "\12\47\1\15\6\6\57\47\14\113\5\6\12\113\6\6"+
    "\4\113\1\6\10\47\2\6\2\47\2\6\26\47\1\6"+
    "\7\47\1\6\2\47\1\6\5\47\1\6\2\113\1\47"+
    "\7\113\2\6\2\113\2\6\3\113\2\6\1\47\6\6"+
    "\1\113\5\6\5\47\2\113\2\6\7\113\3\6\5\113"+
    "\213\6\65\47\22\113\4\47\5\15\12\113\1\6\1\15"+
    "\1\6\1\15\1\113\1\47\2\114\36\6\60\47\24\113"+
    "\2\47\1\15\1\47\10\6\12\113\246\6\57\47\7\113"+
    "\2\6\11\113\27\15\4\47\2\113\42\6\60\47\21\113"+
    "\3\15\1\47\13\6\12\113\6\6\15\15\23\6\53\47"+
    "\15\113\1\47\7\6\12\113\66\6\33\47\2\6\17\113"+
    "\4\6\12\113\6\15\7\114\271\6\54\47\17\113\1\15"+
    "\144\6\100\47\12\113\11\15\14\6\1\47\7\114\2\6"+
    "\1\114\2\6\10\114\1\6\2\114\1\6\30\114\6\0"+
    "\1\6\2\0\2\6\4\0\1\114\1\0\1\114\2\0"+
    "\14\6\12\0\106\6\10\47\2\6\47\47\7\113\2\6"+
    "\7\113\1\47\1\15\1\47\1\113\33\6\1\47\12\113"+
    "\50\47\7\113\1\47\4\113\10\15\1\113\10\6\1\47"+
    "\13\113\56\47\20\113\3\15\1\47\5\15\15\6\20\114"+
    "\71\47\7\6\11\47\1\6\45\47\10\113\1\6\10\113"+
    "\1\47\5\15\12\6\12\113\23\15\3\6\2\15\36\47"+
    "\2\6\26\113\1\6\16\113\111\6\7\47\1\6\2\47"+
    "\1\6\46\47\6\113\3\6\1\113\1\6\2\113\1\6"+
    "\7\113\1\47\1\113\10\6\12\113\6\6\6\47\1\6"+
    "\2\47\1\6\40\47\5\113\1\6\2\113\1\6\5\113"+
    "\1\47\7\6\12\113\u0136\6\23\47\4\113\2\15\7\6"+
    "\2\0\1\114\1\0\15\114\1\6\42\114\7\0\3\6"+
    "\5\0\15\6\12\0\126\6\1\114\17\6\35\15\4\47"+
    "\21\15\15\6\1\15\232\47\146\6\157\47\1\6\5\15"+
    "\13\6\304\47\u014c\6\141\114\17\6\57\47\1\114\21\0"+
    "\6\114\17\0\252\6\107\47\271\6\71\47\7\6\37\47"+
    "\1\6\12\113\4\6\2\15\117\114\1\6\12\0\6\6"+
    "\36\47\2\6\5\113\1\15\12\6\60\47\7\113\11\15"+
    "\4\47\2\15\12\6\12\113\1\6\7\15\1\6\25\47"+
    "\5\6\23\47\260\6\100\47\33\15\145\6\113\47\4\6"+
    "\1\113\1\47\67\113\7\6\4\113\15\47\100\6\2\47"+
    "\1\15\1\47\1\0\13\6\2\0\16\6\370\47\10\6"+
    "\363\47\u01e3\114\52\6\11\114\u01e7\6\4\114\1\6\7\114"+
    "\1\6\2\114\1\6\37\47\4\114\17\6\1\114\35\6"+
    "\3\47\2\6\1\114\16\6\4\47\10\6\u018c\47\4\6"+
    "\153\47\5\6\15\47\3\6\11\47\7\6\12\47\2\6"+
    "\1\15\2\113\1\15\4\0\134\6\56\0\2\6\27\0"+
    "\271\6\366\15\12\6\47\15\2\6\74\15\5\113\3\15"+
    "\6\113\10\0\10\113\2\15\7\113\36\15\4\113\73\15"+
    "\27\6\102\15\3\113\1\15\232\6\24\15\14\6\127\15"+
    "\11\6\31\15\207\6\125\47\1\6\107\47\1\6\2\47"+
    "\2\6\1\47\2\6\2\47\2\6\4\47\1\6\14\47"+
    "\1\6\1\47\1\6\7\47\1\6\101\47\1\6\4\47"+
    "\2\6\10\47\1\6\7\47\1\6\34\47\1\6\4\47"+
    "\1\6\5\47\1\6\1\47\3\6\7\47\1\6\u0154\47"+
    "\2\6\31\47\1\15\31\47\1\15\37\47\1\15\31\47"+
    "\1\15\37\47\1\15\31\47\1\15\37\47\1\15\31\47"+
    "\1\15\37\47\1\15\31\47\1\15\10\47\2\6\151\113"+
    "\4\15\62\113\10\15\1\113\16\15\1\113\7\15\17\6"+
    "\5\113\1\6\17\113\120\6\37\114\6\6\6\114\325\6"+
    "\7\113\1\6\21\113\2\6\7\113\1\6\2\113\1\6"+
    "\5\113\5\6\76\114\41\6\1\0\160\6\55\47\3\6"+
    "\7\113\7\47\2\6\12\113\4\6\1\47\1\15\u0140\6"+
    "\36\114\1\0\21\6\54\47\16\113\5\6\1\47\320\6"+
    "\34\114\16\0\346\6\7\114\1\6\4\114\1\6\2\114"+
    "\1\6\17\114\1\6\305\47\2\6\11\15\7\113\51\6"+
    "\104\47\7\113\1\47\4\6\12\113\4\6\2\15\u0111\6"+
    "\77\15\1\47\4\15\114\6\75\15\302\6\4\47\1\6"+
    "\33\47\1\6\2\47\1\6\1\47\2\6\1\47\1\6"+
    "\12\47\1\6\4\47\1\6\1\47\1\6\1\47\6\6"+
    "\1\47\4\6\1\47\1\6\1\47\1\6\1\47\1\6"+
    "\3\47\1\6\2\47\1\6\1\47\2\6\1\47\1\6"+
    "\1\47\1\6\1\47\1\6\1\47\1\6\1\47\1\6"+
    "\2\47\1\6\1\47\2\6\4\47\1\6\7\47\1\6"+
    "\4\47\1\6\4\47\1\6\1\47\1\6\12\47\1\6"+
    "\21\47\5\6\3\47\1\6\5\47\1\6\21\47\64\6"+
    "\2\15\16\6\54\15\4\6\144\15\14\6\17\15\2\6"+
    "\17\15\1\6\17\15\1\6\45\15\12\6\15\15\3\6"+
    "\135\15\3\6\75\15\71\6\35\15\15\6\54\15\4\6"+
    "\11\15\7\6\2\15\16\6\6\15\232\6\326\15\12\6"+
    "\15\15\3\6\13\15\5\6\164\15\14\6\131\15\7\6"+
    "\14\15\24\6\14\15\4\6\70\15\10\6\12\15\6\6"+
    "\50\15\10\6\36\15\122\6\14\15\1\6\145\15\1\6"+
    "\4\15\3\6\51\15\2\6\6\15\3\6\35\15\2\6"+
    "\207\15\14\6\16\15\2\6\4\15\4\6\3\15\5\6"+
    "\3\15\15\6\6\15\u015a\6\12\0\6\6\327\47\11\114"+
    "\40\6\65\47\5\114\6\6\336\47\2\6\u0182\47\16\6"+
    "\u0131\47\37\6\36\47\342\6\113\114\5\6\u0160\114\121\6"+
    "\1\0\36\6\140\0\200\6\360\113\20\6";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[37632];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\1\1\3\1\4\1\5"+
    "\1\4\1\6\1\7\2\4\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\10\24\1\25\2\24\1\4\1\26\1\1\1\27\1\30"+
    "\1\31\1\4\1\32\1\0\1\6\1\33\2\0\1\34"+
    "\1\35\1\36\12\24\1\37\1\0\1\40\1\41\2\0"+
    "\1\42\4\24\1\43\5\24\3\0\1\6\7\24\11\0"+
    "\4\24\1\44\1\45\7\0\1\46\1\47\1\0\1\50"+
    "\1\24\1\51\6\0\1\52\1\53\1\54\16\0\1\55"+
    "\3\0\1\56";

  private static int [] zzUnpackAction() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\116\0\234\0\352\0\234\0\352\0\u0138\0\u0186"+
    "\0\234\0\u01d4\0\u0222\0\234\0\u0270\0\234\0\234\0\234"+
    "\0\234\0\234\0\234\0\234\0\u02be\0\u030c\0\u035a\0\u03a8"+
    "\0\u03f6\0\234\0\u0444\0\u0492\0\u04e0\0\u052e\0\u057c\0\u05ca"+
    "\0\u0618\0\u0666\0\234\0\u06b4\0\u0702\0\u0750\0\234\0\u0444"+
    "\0\u079e\0\234\0\u07ec\0\u083a\0\234\0\u0888\0\u08d6\0\234"+
    "\0\u0924\0\u0972\0\234\0\234\0\234\0\u09c0\0\u0a0e\0\u0a5c"+
    "\0\u0aaa\0\u0af8\0\u0b46\0\u0b94\0\u0be2\0\u0c30\0\u0c7e\0\234"+
    "\0\u0ccc\0\234\0\234\0\u0d1a\0\u0d68\0\u0972\0\u0db6\0\u0e04"+
    "\0\u0e52\0\u0ea0\0\u0444\0\u0eee\0\u0f3c\0\u0f8a\0\u0fd8\0\u1026"+
    "\0\u1074\0\u10c2\0\u1110\0\234\0\u115e\0\u11ac\0\u11fa\0\u1248"+
    "\0\u1296\0\u12e4\0\u1332\0\u1380\0\u13ce\0\u141c\0\u146a\0\u14b8"+
    "\0\u1506\0\u1554\0\u15a2\0\u15f0\0\u163e\0\u168c\0\u16da\0\u1728"+
    "\0\234\0\234\0\u1776\0\u17c4\0\u1812\0\u1860\0\u18ae\0\u18fc"+
    "\0\u194a\0\234\0\234\0\u1998\0\u0444\0\u19e6\0\u0444\0\u1a34"+
    "\0\u1a82\0\u1ad0\0\u1b1e\0\u1b6c\0\u1bba\0\234\0\u0444\0\234"+
    "\0\u1c08\0\u1c56\0\u1ca4\0\u1cf2\0\u1d40\0\u1d8e\0\u1ddc\0\u1e2a"+
    "\0\u1e78\0\u1ec6\0\u1f14\0\u1f62\0\u1fb0\0\u1ffe\0\234\0\u204c"+
    "\0\u209a\0\u20e8\0\234";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\3\1\6\1\7\1\3\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\16\1\25\2\26\1\16"+
    "\1\27\1\30\1\31\1\32\1\16\1\33\1\34\4\33"+
    "\1\35\7\33\1\36\1\37\1\40\2\33\1\41\1\42"+
    "\3\16\1\43\12\33\1\44\3\33\1\45\2\33\1\46"+
    "\1\47\1\3\1\16\1\50\1\0\2\51\1\0\2\51"+
    "\1\0\2\51\1\52\24\51\1\53\26\51\1\54\31\51"+
    "\117\0\1\4\2\0\1\4\113\0\1\5\122\0\1\55"+
    "\134\0\2\56\6\0\6\56\23\0\5\56\22\0\1\13"+
    "\1\57\4\0\4\57\1\13\13\57\2\13\6\57\25\13"+
    "\4\57\21\13\2\57\1\33\2\13\15\0\1\60\121\0"+
    "\1\61\121\0\1\62\1\0\2\26\120\0\1\63\115\0"+
    "\1\64\115\0\1\65\63\0\1\33\11\0\1\33\13\0"+
    "\2\33\6\0\25\33\4\0\21\33\2\0\3\33\1\0"+
    "\1\33\11\0\1\33\13\0\2\33\6\0\13\33\1\66"+
    "\11\33\4\0\21\33\2\0\3\33\1\0\1\33\11\0"+
    "\1\33\13\0\2\33\6\0\17\33\1\67\5\33\4\0"+
    "\21\33\2\0\3\33\1\0\1\33\11\0\1\33\13\0"+
    "\2\33\6\0\22\33\1\70\2\33\4\0\21\33\2\0"+
    "\3\33\1\0\1\33\11\0\1\33\13\0\2\33\6\0"+
    "\4\33\1\71\20\33\4\0\21\33\2\0\3\33\1\0"+
    "\1\33\11\0\1\33\13\0\2\33\6\0\12\33\1\72"+
    "\12\33\4\0\21\33\2\0\3\33\1\0\1\33\11\0"+
    "\1\33\13\0\2\33\6\0\7\33\1\73\15\33\4\0"+
    "\21\33\2\0\3\33\1\0\1\33\11\0\1\33\13\0"+
    "\2\33\6\0\4\33\1\74\20\33\4\0\21\33\2\0"+
    "\3\33\1\0\1\33\11\0\1\33\13\0\2\33\6\0"+
    "\25\33\4\0\20\33\1\75\2\0\3\33\1\0\1\33"+
    "\11\0\1\33\13\0\2\33\6\0\25\33\4\0\14\33"+
    "\1\76\2\33\1\77\1\33\2\0\3\33\111\0\1\100"+
    "\5\0\2\51\1\0\2\51\1\0\2\51\1\0\24\51"+
    "\1\0\26\51\1\0\31\51\63\0\1\101\42\0\1\102"+
    "\70\0\1\103\42\0\2\104\6\0\6\104\23\0\5\104"+
    "\22\0\2\57\4\0\104\57\1\0\2\57\1\0\20\61"+
    "\1\105\75\61\26\0\2\106\66\0\1\33\11\0\1\33"+
    "\13\0\2\33\6\0\1\107\21\33\1\110\2\33\4\0"+
    "\21\33\2\0\3\33\1\0\1\33\11\0\1\33\13\0"+
    "\2\33\6\0\4\33\1\111\20\33\4\0\21\33\2\0"+
    "\3\33\1\0\1\33\11\0\1\33\13\0\2\33\6\0"+
    "\17\33\1\112\5\33\4\0\21\33\2\0\3\33\1\0"+
    "\1\33\11\0\1\33\13\0\2\33\6\0\3\33\1\113"+
    "\21\33\4\0\21\33\2\0\3\33\1\0\1\33\11\0"+
    "\1\33\13\0\2\33\6\0\24\33\1\113\4\0\21\33"+
    "\2\0\3\33\1\0\1\33\11\0\1\33\13\0\2\33"+
    "\6\0\10\33\1\114\14\33\4\0\21\33\2\0\3\33"+
    "\1\0\1\33\11\0\1\33\13\0\2\33\6\0\13\33"+
    "\1\115\11\33\4\0\21\33\2\0\3\33\1\0\1\33"+
    "\11\0\1\33\13\0\2\33\6\0\25\33\4\0\11\33"+
    "\1\116\7\33\2\0\3\33\1\0\1\33\11\0\1\33"+
    "\13\0\2\33\6\0\25\33\4\0\4\33\1\117\14\33"+
    "\2\0\3\33\1\0\1\33\11\0\1\33\13\0\2\33"+
    "\6\0\25\33\4\0\15\33\1\120\3\33\2\0\3\33"+
    "\31\0\1\121\1\122\112\0\2\123\6\0\6\123\23\0"+
    "\5\123\22\0\20\61\1\105\4\61\1\124\70\61\1\33"+
    "\11\0\1\33\13\0\2\33\6\0\2\33\1\125\22\33"+
    "\4\0\21\33\2\0\3\33\1\0\1\33\11\0\1\33"+
    "\13\0\2\33\6\0\4\33\1\113\20\33\4\0\21\33"+
    "\2\0\3\33\1\0\1\33\11\0\1\33\13\0\2\33"+
    "\6\0\4\33\1\126\20\33\4\0\21\33\2\0\3\33"+
    "\1\0\1\33\11\0\1\33\13\0\2\33\6\0\16\33"+
    "\1\127\6\33\4\0\21\33\2\0\3\33\1\0\1\33"+
    "\11\0\1\33\13\0\2\33\6\0\21\33\1\110\3\33"+
    "\4\0\21\33\2\0\3\33\1\0\1\33\11\0\1\33"+
    "\13\0\2\33\6\0\13\33\1\130\11\33\4\0\21\33"+
    "\2\0\3\33\1\0\1\33\11\0\1\33\13\0\2\33"+
    "\6\0\25\33\4\0\1\33\1\131\17\33\2\0\3\33"+
    "\1\0\1\33\11\0\1\33\13\0\2\33\6\0\25\33"+
    "\4\0\2\33\1\132\16\33\2\0\3\33\1\0\1\33"+
    "\11\0\1\33\13\0\2\33\6\0\25\33\4\0\7\33"+
    "\1\133\11\33\2\0\3\33\17\0\1\134\1\135\46\0"+
    "\1\136\2\0\1\137\3\0\1\140\7\0\1\141\2\0"+
    "\1\142\34\0\1\143\1\0\1\122\112\0\2\144\6\0"+
    "\6\144\23\0\5\144\22\0\1\33\11\0\1\33\13\0"+
    "\2\33\6\0\12\33\1\113\12\33\4\0\21\33\2\0"+
    "\3\33\1\0\1\33\11\0\1\33\13\0\2\33\6\0"+
    "\14\33\1\113\10\33\4\0\21\33\2\0\3\33\1\0"+
    "\1\33\11\0\1\33\13\0\2\33\6\0\13\33\1\110"+
    "\11\33\4\0\21\33\2\0\3\33\1\0\1\33\11\0"+
    "\1\33\13\0\2\33\6\0\15\33\1\145\7\33\4\0"+
    "\21\33\2\0\3\33\1\0\1\33\11\0\1\33\13\0"+
    "\2\33\6\0\25\33\4\0\4\33\1\146\14\33\2\0"+
    "\3\33\1\0\1\33\11\0\1\33\13\0\2\33\6\0"+
    "\25\33\4\0\7\33\1\147\11\33\2\0\3\33\1\0"+
    "\1\33\11\0\1\33\13\0\2\33\6\0\25\33\4\0"+
    "\12\33\1\150\6\33\2\0\3\33\17\0\1\134\46\0"+
    "\1\151\47\0\1\135\45\0\1\152\116\0\1\153\116\0"+
    "\1\154\121\0\1\155\111\0\1\156\3\0\1\157\4\0"+
    "\1\160\5\0\1\161\74\0\1\162\22\0\1\142\34\0"+
    "\1\143\35\0\1\163\56\0\2\164\6\0\6\164\23\0"+
    "\5\164\22\0\1\33\11\0\1\33\13\0\2\33\6\0"+
    "\23\33\1\113\1\33\4\0\21\33\2\0\3\33\1\0"+
    "\1\33\11\0\1\33\13\0\2\33\6\0\25\33\4\0"+
    "\15\33\1\165\3\33\2\0\3\33\1\0\1\33\11\0"+
    "\1\33\13\0\2\33\6\0\25\33\4\0\1\166\20\33"+
    "\2\0\3\33\1\0\1\33\11\0\1\33\13\0\2\33"+
    "\6\0\25\33\4\0\5\33\1\167\13\33\2\0\3\33"+
    "\31\0\1\170\173\0\1\153\76\0\1\171\120\0\1\172"+
    "\127\0\1\173\107\0\1\174\106\0\1\175\54\0\2\176"+
    "\6\0\6\176\23\0\5\176\22\0\1\33\11\0\1\33"+
    "\13\0\2\33\6\0\25\33\4\0\10\33\1\177\10\33"+
    "\2\0\3\33\66\0\1\200\134\0\1\201\41\0\1\202"+
    "\163\0\1\203\116\0\1\204\122\0\1\205\117\0\1\206"+
    "\74\0\1\151\132\0\1\207\106\0\1\210\45\0\1\211"+
    "\4\0\1\212\115\0\1\213\174\0\1\214\36\0\1\215"+
    "\113\0\2\216\114\0\2\216\35\0\1\217\115\0\1\163"+
    "\135\0\1\220\75\0\1\152\56\0\2\216\1\221\115\0"+
    "\1\222\152\0\1\223\115\0\1\162\30\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8502];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\3\1\1\11\2\1\1\11"+
    "\1\1\7\11\5\1\1\11\10\1\1\11\3\1\1\11"+
    "\2\1\1\11\2\1\1\11\1\0\1\1\1\11\2\0"+
    "\3\11\12\1\1\11\1\0\2\11\2\0\13\1\3\0"+
    "\1\11\7\1\11\0\4\1\2\11\7\0\2\11\1\0"+
    "\3\1\6\0\1\11\1\1\1\11\16\0\1\11\3\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[147];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    /****************** Codigo de usuario (codigo java) ***********************/

    //StringBuilder para cadenas de texto
    private StringBuilder string;

 /*-----------------------------------------------
                   Codigo del lexer
             -------------------------------------------------*/

    private List<ErrorAnalisis> errorLexList;

    public List<ErrorAnalisis> getLexicalErrors(){
        return this.errorLexList;
    }

    private void reportError(String message, String text){
         errorLexList.add(new ErrorAnalisis(text,"Lexico",message,(yyline+1),(yycolumn+1)));
    }

    /*-------------------------- Codigo para el parser --------------------------------*/


     /*-----------------------------------------------
              Codigo para el parser
        -------------------------------------------------*/

    private Symbol symbol(int type, Object object){
        return new Symbol(type, yyline+1, yycolumn+1, object);
    }

    private Symbol symbol(int type){
        return new Symbol(type, yyline+1, yycolumn+1);
    }


    /*Created by Pablo*/


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerForms(java.io.Reader in) {
      /****************** codigo dentro del constructor ******************/
    errorLexList = new ArrayList<>();
    string = new StringBuilder();

    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* ignorar */
            }
          // fall through
          case 47: break;
          case 2:
            { return symbol(sym.WHITESPACE, yytext());
            }
          // fall through
          case 48: break;
          case 3:
            { return symbol(sym.NEWLINE, yytext());
            }
          // fall through
          case 49: break;
          case 4:
            { reportError("Simbolo no existe en el lenguaje", yytext());
                    return symbol(sym.ERROR, yytext());
            }
          // fall through
          case 50: break;
          case 5:
            { yybegin(STRING);
              return symbol(sym.INICIO_CADENA);
            }
          // fall through
          case 51: break;
          case 6:
            { /*Ignorado*/
            }
          // fall through
          case 52: break;
          case 7:
            { return symbol(sym.MODULO);
            }
          // fall through
          case 53: break;
          case 8:
            { return symbol(sym.PARENT_APERTURA);
            }
          // fall through
          case 54: break;
          case 9:
            { return symbol(sym.PARENT_CIERRE);
            }
          // fall through
          case 55: break;
          case 10:
            { return symbol(sym.MULTIPLICACION);
            }
          // fall through
          case 56: break;
          case 11:
            { return symbol(sym.SUMA);
            }
          // fall through
          case 57: break;
          case 12:
            { return symbol(sym.COMA);
            }
          // fall through
          case 58: break;
          case 13:
            { return symbol(sym.RESTA);
            }
          // fall through
          case 59: break;
          case 14:
            { return symbol(sym.DIVISION);
            }
          // fall through
          case 60: break;
          case 15:
            { return symbol(sym.ENTERO, Integer.parseInt(yytext()));
            }
          // fall through
          case 61: break;
          case 16:
            { return symbol(sym.MENOR);
            }
          // fall through
          case 62: break;
          case 17:
            { return symbol(sym.IGUALACION);
            }
          // fall through
          case 63: break;
          case 18:
            { return symbol(sym.MAYOR);
            }
          // fall through
          case 64: break;
          case 19:
            { return symbol(sym.COMODIN);
            }
          // fall through
          case 65: break;
          case 20:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 66: break;
          case 21:
            { return symbol(sym.POTENCIA);
            }
          // fall through
          case 67: break;
          case 22:
            { return symbol(sym.NOT);
            }
          // fall through
          case 68: break;
          case 23:
            { return symbol(sym.TEXTO_PLANO, yytext());
            }
          // fall through
          case 69: break;
          case 24:
            { yybegin(YYINITIAL);
        return symbol(sym.FIN_CADENA);
            }
          // fall through
          case 70: break;
          case 25:
            { return symbol(sym.TEXTO_PLANO, "@");
            }
          // fall through
          case 71: break;
          case 26:
            { return symbol(sym.DIFERENTE);
            }
          // fall through
          case 72: break;
          case 27:
            { return symbol(sym.AND);
            }
          // fall through
          case 73: break;
          case 28:
            { return symbol(sym.MENOR_IGUAL);
            }
          // fall through
          case 74: break;
          case 29:
            { return symbol(sym.IGUALDAD);
            }
          // fall through
          case 75: break;
          case 30:
            { return symbol(sym.MAYOR_IGUAL);
            }
          // fall through
          case 76: break;
          case 31:
            { return symbol(sym.OR);
            }
          // fall through
          case 77: break;
          case 32:
            { return symbol(sym.TEXTO_PLANO, "\"");
            }
          // fall through
          case 78: break;
          case 33:
            { return symbol(sym.TEXTO_PLANO, "\n");
            }
          // fall through
          case 79: break;
          case 34:
            { return symbol(sym.DECIMAL, Double.parseDouble(yytext()));
            }
          // fall through
          case 80: break;
          case 35:
            { return symbol(sym.COLOR_PRESET, yytext());
            }
          // fall through
          case 81: break;
          case 36:
            { return symbol(sym.EMOJI_SAD, yytext());
            }
          // fall through
          case 82: break;
          case 37:
            { return symbol(sym.EMOJI_SMILE, yytext());
            }
          // fall through
          case 83: break;
          case 38:
            { return symbol(sym.EMOJI_SERIOUS, yytext());
            }
          // fall through
          case 84: break;
          case 39:
            { return symbol(sym.EMOJI_HEART, yytext());
            }
          // fall through
          case 85: break;
          case 40:
            { return symbol(sym.VAR_NUMERO);
            }
          // fall through
          case 86: break;
          case 41:
            { return symbol(sym.VAR_STRING);
            }
          // fall through
          case 87: break;
          case 42:
            { return symbol(sym.COLOR_HEX, yytext());
            }
          // fall through
          case 88: break;
          case 43:
            { return symbol(sym.VAR_ESPECIAL);
            }
          // fall through
          case 89: break;
          case 44:
            { return symbol(sym.EMOJI_CAT, yytext());
            }
          // fall through
          case 90: break;
          case 45:
            { return symbol(sym.EMOJI_STAR, yytext());
            }
          // fall through
          case 91: break;
          case 46:
            { return symbol(sym.EMOJI_MULTI_STAR, yytext());
            }
          // fall through
          case 92: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
