
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.pablocompany.proyectono1_compi1.compiler.logic.fuente;

import java_cup.runtime.*;
import java.util.*;
import com.pablocompany.proyectono1_compi1.compiler.models.errores.ErrorAnalisis;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.estiloscompiled.estilosmodels.*;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.estiloscompiled.*;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.*;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.compiledlayouts.*;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.compiledforms.compiledquests.*;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.compiledforms.*;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.cadenastexto.*;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.colorescompiled.*;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.colorescompiled.colorescompilados.*;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.codigofuente.expresiones.fragmentos.TipoEmoji;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserCompiled extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SymCompiled.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserCompiled() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserCompiled(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserCompiled(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\063\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\003\004\000\002\004\003" +
    "\000\002\004\003\000\002\006\030\000\002\006\027\000" +
    "\002\012\004\000\002\012\003\000\002\012\004\000\002" +
    "\013\011\000\002\014\004\000\002\014\003\000\002\015" +
    "\011\000\002\005\003\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\016\011\000\002\016\004\000" +
    "\002\025\004\000\002\025\003\000\002\025\004\000\002" +
    "\026\007\000\002\026\010\000\002\026\010\000\002\026" +
    "\010\000\002\026\015\000\002\024\003\000\002\024\003" +
    "\000\002\017\003\000\002\017\011\000\002\017\011\000" +
    "\002\017\003\000\002\023\003\000\002\023\003\000\002" +
    "\020\004\000\002\020\005\000\002\021\004\000\002\021" +
    "\003\000\002\021\004\000\002\022\003\000\002\022\003" +
    "\000\002\022\003\000\002\022\003\000\002\022\003\000" +
    "\002\022\003\000\002\022\003\000\002\022\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\164\000\004\033\007\001\002\000\010\002\000\003" +
    "\165\033\007\001\002\000\004\002\164\001\002\000\010" +
    "\002\ufffb\003\ufffb\033\ufffb\001\002\000\004\022\012\001" +
    "\002\000\010\002\ufffe\003\ufffe\033\ufffe\001\002\000\010" +
    "\002\ufffc\003\ufffc\033\ufffc\001\002\000\004\005\013\001" +
    "\002\000\006\045\015\046\016\001\002\000\004\006\017" +
    "\001\002\000\010\006\uffdc\034\uffdc\037\uffdc\001\002\000" +
    "\010\006\uffdd\034\uffdd\037\uffdd\001\002\000\006\045\015" +
    "\046\016\001\002\000\004\006\021\001\002\000\006\045" +
    "\015\046\016\001\002\000\004\006\023\001\002\000\006" +
    "\045\015\046\016\001\002\000\004\034\025\001\002\000" +
    "\004\033\030\001\002\000\006\003\150\033\152\001\002" +
    "\000\006\003\uffea\033\uffea\001\002\000\016\012\032\013" +
    "\034\014\035\015\036\020\031\023\033\001\002\000\004" +
    "\006\135\001\002\000\004\034\076\001\002\000\004\017" +
    "\072\001\002\000\004\005\067\001\002\000\004\013\043" +
    "\001\002\000\004\016\037\001\002\000\004\005\040\001" +
    "\002\000\004\051\041\001\002\000\004\031\042\001\002" +
    "\000\006\003\uffe6\033\uffe6\001\002\000\004\005\044\001" +
    "\002\000\012\033\046\036\051\044\047\052\050\001\002" +
    "\000\004\031\066\001\002\000\006\045\015\046\016\001" +
    "\002\000\004\031\uffe1\001\002\000\004\031\uffde\001\002" +
    "\000\006\045\015\046\016\001\002\000\004\006\053\001" +
    "\002\000\006\045\015\046\016\001\002\000\004\006\055" +
    "\001\002\000\006\045\015\046\016\001\002\000\004\037" +
    "\057\001\002\000\004\031\uffe0\001\002\000\004\006\061" +
    "\001\002\000\006\045\015\046\016\001\002\000\004\006" +
    "\063\001\002\000\006\045\015\046\016\001\002\000\004" +
    "\034\065\001\002\000\004\031\uffdf\001\002\000\006\003" +
    "\uffe7\033\uffe7\001\002\000\012\033\046\036\051\044\047" +
    "\052\050\001\002\000\004\031\071\001\002\000\006\003" +
    "\uffe8\033\uffe8\001\002\000\004\005\073\001\002\000\006" +
    "\045\015\046\016\001\002\000\004\034\075\001\002\000" +
    "\006\003\uffe5\033\uffe5\001\002\000\004\033\100\001\002" +
    "\000\010\003\125\032\126\033\100\001\002\000\004\050" +
    "\102\001\002\000\010\003\ufff7\032\ufff7\033\ufff7\001\002" +
    "\000\004\034\103\001\002\000\004\033\106\001\002\000" +
    "\006\032\121\033\106\001\002\000\006\032\ufff3\033\ufff3" +
    "\001\002\000\004\024\107\001\002\000\004\034\110\001" +
    "\002\000\004\033\007\001\002\000\004\032\116\001\002" +
    "\000\004\032\uffef\001\002\000\004\032\ufff0\001\002\000" +
    "\004\032\uffee\001\002\000\004\032\ufff1\001\002\000\004" +
    "\024\117\001\002\000\004\034\120\001\002\000\006\032" +
    "\ufff2\033\ufff2\001\002\000\004\050\123\001\002\000\006" +
    "\032\ufff4\033\ufff4\001\002\000\004\034\124\001\002\000" +
    "\010\003\ufff5\032\ufff5\033\ufff5\001\002\000\010\003\ufff6" +
    "\032\ufff6\033\ufff6\001\002\000\004\012\130\001\002\000" +
    "\010\003\ufff8\032\ufff8\033\ufff8\001\002\000\004\034\131" +
    "\001\002\000\004\032\132\001\002\000\004\022\133\001" +
    "\002\000\004\034\134\001\002\000\012\002\ufff9\003\ufff9" +
    "\032\ufff9\033\ufff9\001\002\000\006\045\015\046\016\001" +
    "\002\000\004\006\137\001\002\000\006\047\141\050\140" +
    "\001\002\000\004\006\uffe2\001\002\000\004\006\uffe3\001" +
    "\002\000\004\006\143\001\002\000\004\013\144\001\002" +
    "\000\004\005\145\001\002\000\012\033\046\036\051\044" +
    "\047\052\050\001\002\000\004\031\147\001\002\000\006" +
    "\003\uffe4\033\uffe4\001\002\000\006\003\uffe9\033\uffe9\001" +
    "\002\000\006\003\uffeb\033\uffeb\001\002\000\016\012\153" +
    "\013\034\014\035\015\036\020\031\023\033\001\002\000" +
    "\004\034\154\001\002\000\004\033\100\001\002\000\010" +
    "\003\125\032\156\033\100\001\002\000\004\012\157\001" +
    "\002\000\004\034\160\001\002\000\004\032\161\001\002" +
    "\000\004\022\162\001\002\000\004\034\163\001\002\000" +
    "\012\002\ufffa\003\ufffa\032\ufffa\033\ufffa\001\002\000\004" +
    "\002\001\001\002\000\010\002\ufffd\003\ufffd\033\ufffd\001" +
    "\002\000\010\002\uffff\003\uffff\033\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\164\000\014\002\004\003\003\004\007\006\010\007" +
    "\005\001\001\000\010\004\165\006\010\007\005\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\023\013\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\023\017\001\001\000\002\001\001" +
    "\000\004\023\021\001\001\000\002\001\001\000\004\023" +
    "\023\001\001\000\002\001\001\000\006\025\025\026\026" +
    "\001\001\000\004\026\150\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\017\044\001" +
    "\001\000\002\001\001\000\004\023\057\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\023\051\001\001\000" +
    "\002\001\001\000\004\023\053\001\001\000\002\001\001" +
    "\000\004\023\055\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\023\061\001\001\000\002" +
    "\001\001\000\004\023\063\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\017\067\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\023\073\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\012\076\013\100\001\001\000\004\013\126\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\014\103\015\104\001\001\000\004\015\121\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\005\110\006\114\007\112\010\111\011\113\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\023\135\001\001\000\002\001\001" +
    "\000\004\024\141\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\017\145\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\012\154\013\100\001\001\000" +
    "\004\013\126\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserCompiled$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserCompiled$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserCompiled$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




       LexerCompiled lex;
       private List<ErrorAnalisis> syntaxErrorListCompiled;

       // conexion de parser y lexer
       public ParserCompiled(LexerCompiled lex){
           super(lex);
           this.lex = lex;
           syntaxErrorListCompiled = new ArrayList<>();
       }

       // Getters
       public LexerCompiled getLexer(){
           return this.lex;
       }

       public List<ErrorAnalisis> getSyntaxErrorList(){
           return this.syntaxErrorListCompiled;
       }

        //Metodo que permite retornar los errores sintacticos del interprete
        public void syntax_error(Symbol simbolo) {
            List<Integer> ids = expected_token_ids();
            List<String> list = new ArrayList<>();

            if (ids.isEmpty()) {
                reportarErrorContextual(simbolo);
                return;
            }

            for (Integer id : ids) {
                list.add(traductor(symbl_name_from_id(id)));
            }

            String esperado = String.join(", ", list);
            String encontrado = (simbolo.value != null) ? simbolo.value.toString() : traductor(symbl_name_from_id(simbolo.sym));

            syntaxErrorListCompiled.add(new ErrorAnalisis(
                encontrado,
                "Sintactico",
                "Se esperaba: \"" + esperado + "\". Pero se encontro con: \"" + encontrado + "\"",
                simbolo.left,
                simbolo.right
            ));
        }

        public void unrecovered_syntax_error(Symbol simbolo) throws Exception {
            String encontrado = (simbolo.value != null) ? simbolo.value.toString() : traductor(symbl_name_from_id(simbolo.sym));
            syntaxErrorListCompiled.add(new ErrorAnalisis(
                encontrado,
                "Sintactico",
                "No se pudo recuperar el analisis cerca de: \"" + encontrado + "\".",
                simbolo.left,
                simbolo.right
            ));
        }

        private void reportarErrorContextual(Symbol simbolo) {

            String tokenEncontrado = (simbolo.value != null) ? simbolo.value.toString() : symbl_name_from_id(simbolo.sym);

            String mensaje = "Error de sintaxis cerca de \"" + tokenEncontrado + "\". ";

            if (tokenEncontrado.equals("TABLE") || tokenEncontrado.equals("SECTION")) {

                mensaje += "Asegurate de que la etiqueta este bien cerrada con \">\" o \"/>\".";

            } else if (tokenEncontrado.equals("IGUAL")) {

                mensaje += "Parece que faltan los parametros de layout (width, height, pointX, pointY).";

            } else {

                mensaje += "Revisa la estructura de las etiquetas anidadas.";

            }

            syntaxErrorListCompiled.add(new ErrorAnalisis(tokenEncontrado, "Sintactico", mensaje, simbolo.left, simbolo.right));
        }

        private String traductor(String nombre) {
            switch (nombre) {
                case "MENOR": return "\" < \"";
                case "MAYOR": return "\" > \"";
                case "IGUAL": return "\" = \"";
                case "DIAGONAL": return "\" / \"";
                case "CIERRE_ETIQUETA": return "\" /> \"";
                case "INICIO_ETIQUETA": return "\" </ \"";
                case "COMA": return "\" , \"";
                case "PARENT_APERTURA": return "\" ( \"";
                case "PARENT_CIERRE": return "\" ) \"";
                case "LLAVE_APERTURA": return "\" { \"";
                case "LLAVE_CIERRE": return "\" } \"";
                case "COLOR_HEX": return "un color hexadecimal (ej: #FFFFFF)";
                case "ENTERO": return "un valor numerico";
                case "TEXTO_PLANO": return "texto";
                case "TABLE": return "etiqueta <table>";
                case "SECTION": return "etiqueta <section>";
                case "LINE": return "etiqueta <line>";
                case "ELEMENT": return "etiqueta <element>";
                case "EOF": return "Final del documento";
                default: return nombre.toLowerCase().replace("_", " ");
            }
        }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserCompiled$actions {
  private final ParserCompiled parser;

  /** Constructor */
  CUP$ParserCompiled$actions(ParserCompiled parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserCompiled$do_action_part00000000(
    int                        CUP$ParserCompiled$act_num,
    java_cup.runtime.lr_parser CUP$ParserCompiled$parser,
    java.util.Stack            CUP$ParserCompiled$stack,
    int                        CUP$ParserCompiled$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserCompiled$result;

      /* select the action based on the action number */
      switch (CUP$ParserCompiled$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= compilado EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		CodigoInterpretado start_val = (CodigoInterpretado)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		RESULT = start_val;
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserCompiled$parser.done_parsing();
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // compilado ::= cuerpo_etiquetas 
            {
              CodigoInterpretado RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		List<CompiledForm> list = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        RESULT = new CodigoInterpretado(list);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("compilado",0, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // cuerpo_etiquetas ::= cuerpo_etiquetas etiqueta_principal 
            {
              List<CompiledForm> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<CompiledForm> list = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledContenedor e = (CompiledContenedor)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            list.add(e);
                            RESULT = list;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("cuerpo_etiquetas",1, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // cuerpo_etiquetas ::= etiqueta_principal 
            {
              List<CompiledForm> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledContenedor e = (CompiledContenedor)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            List<CompiledForm> list = new ArrayList<>();
                            list.add(e);
                            RESULT = list;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("cuerpo_etiquetas",1, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // cuerpo_etiquetas ::= cuerpo_etiquetas error 
            {
              List<CompiledForm> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<CompiledForm> list = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                            RESULT = list;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("cuerpo_etiquetas",1, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // etiqueta_principal ::= etiqueta_tabla 
            {
              CompiledContenedor RESULT =null;
		int tablaleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int tablaright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledTable tabla = (CompiledTable)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = tabla;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta_principal",2, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // etiqueta_principal ::= etiqueta_section 
            {
              CompiledContenedor RESULT =null;
		int secleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int secright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledSection sec = (CompiledSection)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = sec;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta_principal",2, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // etiqueta_tabla ::= MENOR TABLE IGUAL valor_numerico COMA valor_numerico COMA valor_numerico COMA valor_numerico MAYOR lista_estilos MENOR CONTENT MAYOR filas_tabla INICIO_ETIQUETA CONTENT MAYOR INICIO_ETIQUETA TABLE MAYOR 
            {
              CompiledTable RESULT =null;
		int tableft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-20)).left;
		int tabright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-20)).right;
		Object tab = (Object)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-20)).value;
		int wleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-18)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-18)).right;
		Number w = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-18)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-16)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-16)).right;
		Number h = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-16)).value;
		int pointxleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-14)).left;
		int pointxright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-14)).right;
		Number pointx = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-14)).value;
		int pointyleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-12)).left;
		int pointyright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-12)).right;
		Number pointy = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-12)).value;
		int estilosleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-10)).left;
		int estilosright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-10)).right;
		List<CompiledEstilos> estilos = (List<CompiledEstilos>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-10)).value;
		int filasleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)).left;
		int filasright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)).right;
		List<List<CompiledForm>> filas = (List<List<CompiledForm>>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)).value;
		
                        RESULT = new CompiledTable(w, h, pointx, pointy, filas, estilos,tableft, tabright);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta_tabla",4, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-21)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // etiqueta_tabla ::= MENOR TABLE IGUAL valor_numerico COMA valor_numerico COMA valor_numerico COMA valor_numerico MAYOR MENOR CONTENT MAYOR filas_tabla INICIO_ETIQUETA CONTENT MAYOR INICIO_ETIQUETA TABLE MAYOR 
            {
              CompiledTable RESULT =null;
		int tableft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-19)).left;
		int tabright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-19)).right;
		Object tab = (Object)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-19)).value;
		int wleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-17)).left;
		int wright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-17)).right;
		Number w = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-17)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-15)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-15)).right;
		Number h = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-15)).value;
		int pointxleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-13)).left;
		int pointxright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-13)).right;
		Number pointx = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-13)).value;
		int pointyleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-11)).left;
		int pointyright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-11)).right;
		Number pointy = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-11)).value;
		int filasleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)).left;
		int filasright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)).right;
		List<List<CompiledForm>> filas = (List<List<CompiledForm>>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)).value;
		
                        RESULT = new CompiledTable(w, h, pointx, pointy, filas, null,tableft, tabright);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta_tabla",4, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-20)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // filas_tabla ::= filas_tabla fila 
            {
              List<List<CompiledForm>> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<List<CompiledForm>> list = (List<List<CompiledForm>>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		List<CompiledForm> f = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        list.add(f);
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("filas_tabla",8, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // filas_tabla ::= fila 
            {
              List<List<CompiledForm>> RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		List<CompiledForm> f = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        List<List<CompiledForm>> list = new ArrayList<>();
                        list.add(f);
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("filas_tabla",8, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // filas_tabla ::= filas_tabla error 
            {
              List<List<CompiledForm>> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<List<CompiledForm>> list = (List<List<CompiledForm>>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("filas_tabla",8, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // fila ::= MENOR LINE MAYOR celdas_tabla INICIO_ETIQUETA LINE MAYOR 
            {
              List<CompiledForm> RESULT =null;
		int filleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).left;
		int filright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).right;
		List<CompiledForm> fil = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).value;
		
                        RESULT = fil;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("fila",9, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // celdas_tabla ::= celdas_tabla celda 
            {
              List<CompiledForm> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<CompiledForm> list = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledForm c = (CompiledForm)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        list.add(c);
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("celdas_tabla",10, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // celdas_tabla ::= celda 
            {
              List<CompiledForm> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledForm c = (CompiledForm)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        List<CompiledForm> list = new ArrayList<>();
                        list.add(c);
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("celdas_tabla",10, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // celda ::= MENOR ELEMENT MAYOR etiqueta INICIO_ETIQUETA ELEMENT MAYOR 
            {
              CompiledForm RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).right;
		CompiledForm e = (CompiledForm)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).value;
		
                        RESULT = e;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("celda",11, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // etiqueta ::= etiqueta_tabla 
            {
              CompiledForm RESULT =null;
		int tablaleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int tablaright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledTable tabla = (CompiledTable)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = tabla;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta",3, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // etiqueta ::= etiqueta_section 
            {
              CompiledForm RESULT =null;
		int secleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int secright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledSection sec = (CompiledSection)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = sec;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta",3, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // etiqueta ::= etiqueta_text 
            {
              CompiledForm RESULT =null;
		int textoleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int textoright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledText texto = (CompiledText)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = texto;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta",3, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // etiqueta ::= etiqueta_preguntas 
            {
              CompiledForm RESULT =null;
		int preguntasleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int preguntasright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledQuestions preguntas = (CompiledQuestions)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = preguntas;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta",3, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // bloque_estilos ::= MENOR STYLE MAYOR lista_propiedades INICIO_ETIQUETA STYLE MAYOR 
            {
              CompiledEstilos RESULT =null;
		int estilosleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).left;
		int estilosright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).right;
		CompiledEstilos estilos = (CompiledEstilos)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).value;
		
                        RESULT = estilos;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("bloque_estilos",12, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // bloque_estilos ::= error MAYOR 
            {
              CompiledEstilos RESULT =null;

              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("bloque_estilos",12, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // lista_estilos ::= lista_estilos lista_propiedades 
            {
              List<CompiledEstilos> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<CompiledEstilos> list = (List<CompiledEstilos>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		int estleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int estright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledEstilos est = (CompiledEstilos)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        list.add(est);
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_estilos",19, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // lista_estilos ::= lista_propiedades 
            {
              List<CompiledEstilos> RESULT =null;
		int estleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int estright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledEstilos est = (CompiledEstilos)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        List<CompiledEstilos> list = new ArrayList<>();
                        list.add(est);
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_estilos",19, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // lista_estilos ::= lista_estilos error 
            {
              List<CompiledEstilos> RESULT =null;
		int estleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int estright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<CompiledEstilos> est = (List<CompiledEstilos>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                        RESULT = est;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_estilos",19, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // lista_propiedades ::= MENOR COLOR_KEY IGUAL valor_color CIERRE_ETIQUETA 
            {
              CompiledEstilos RESULT =null;
		int color1left = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int color1right = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		CompiledColor color1 = (CompiledColor)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                            RESULT = new CompiledBackground(color1);
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_propiedades",20, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // lista_propiedades ::= MENOR BACKGROUND COLOR_KEY IGUAL valor_color CIERRE_ETIQUETA 
            {
              CompiledEstilos RESULT =null;
		int color2left = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int color2right = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		CompiledColor color2 = (CompiledColor)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                            RESULT = new CompiledTextColor(color2);
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_propiedades",20, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-5)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // lista_propiedades ::= MENOR FONT FAMILY IGUAL TIPOGRAFIA CIERRE_ETIQUETA 
            {
              CompiledEstilos RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		String tipo = (String)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                            RESULT = new CompiledFontFamily(tipo);
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_propiedades",20, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-5)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // lista_propiedades ::= MENOR TEXT SIZE IGUAL valor_numerico MAYOR 
            {
              CompiledEstilos RESULT =null;
		int num1left = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int num1right = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		Number num1 = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                            RESULT = new CompiledTextSize(num1);
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_propiedades",20, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-5)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // lista_propiedades ::= MENOR BORDER COMA valor_numerico COMA valor_borde COMA COLOR_KEY IGUAL valor_color CIERRE_ETIQUETA 
            {
              CompiledEstilos RESULT =null;
		int num2left = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-7)).left;
		int num2right = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-7)).right;
		Number num2 = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-7)).value;
		int grosorleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-5)).left;
		int grosorright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-5)).right;
		String grosor = (String)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-5)).value;
		int colores3left = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int colores3right = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		CompiledColor colores3 = (CompiledColor)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                            RESULT = new CompiledBorder(num2, grosor, colores3);
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_propiedades",20, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-10)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // valor_borde ::= GROSOR_LINEA 
            {
              String RESULT =null;
		int grosorleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int grosorright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		String grosor = (String)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        RESULT = grosor.toString();
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("valor_borde",18, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // valor_borde ::= LINE 
            {
              String RESULT =null;
		int linleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int linright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		String lin = (String)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        RESULT = lin.toString();
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("valor_borde",18, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // valor_color ::= COLOR_HEX 
            {
              CompiledColor RESULT =null;
		int hexleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int hexright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		String hex = (String)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        RESULT = new CompiledHexColor(hex);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("valor_color",13, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // valor_color ::= PARENT_APERTURA valor_numerico COMA valor_numerico COMA valor_numerico PARENT_CIERRE 
            {
              CompiledColor RESULT =null;
		int num1left = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-5)).left;
		int num1right = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-5)).right;
		Number num1 = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-5)).value;
		int num2left = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).left;
		int num2right = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).right;
		Number num2 = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).value;
		int num3left = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int num3right = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		Number num3 = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                        RESULT = new CompiledRgbColor(num1, num2, num3);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("valor_color",13, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // valor_color ::= MENOR valor_numerico COMA valor_numerico COMA valor_numerico MAYOR 
            {
              CompiledColor RESULT =null;
		int num1left = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-5)).left;
		int num1right = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-5)).right;
		Number num1 = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-5)).value;
		int num2left = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).left;
		int num2right = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).right;
		Number num2 = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).value;
		int num3left = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int num3right = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		Number num3 = (Number)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                        RESULT = new CompiledHslColor(num1, num2, num3);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("valor_color",13, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // valor_color ::= COLOR_PRESET 
            {
              CompiledColor RESULT =null;
		int presetleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int presetright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		String preset = (String)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        RESULT = new CompiledPresetColor(preset.toString());
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("valor_color",13, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // valor_numerico ::= ENTERO 
            {
              Number RESULT =null;
		int enteroleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int enteroright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		Integer entero = (Integer)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        RESULT = entero;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("valor_numerico",17, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // valor_numerico ::= DECIMAL 
            {
              Number RESULT =null;
		int decleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int decright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		Double dec = (Double)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        RESULT = dec;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("valor_numerico",17, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // valor_cadena ::= INICIO_CADENA FIN_CADENA 
            {
              CompiledCadenaTexto RESULT =null;
		
                        List<CompiledTexto> texto = new ArrayList<>();
                        texto.add(new CompiledCadena(""));
                        RESULT = new CompiledCadenaTexto(texto);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("valor_cadena",14, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // valor_cadena ::= INICIO_CADENA lista_fragmentos FIN_CADENA 
            {
              CompiledCadenaTexto RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<CompiledTexto> list = (List<CompiledTexto>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                        RESULT = new CompiledCadenaTexto(list);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("valor_cadena",14, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // lista_fragmentos ::= lista_fragmentos fragmento 
            {
              List<CompiledTexto> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<CompiledTexto> list = (List<CompiledTexto>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		int fragleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int fragright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledTexto frag = (CompiledTexto)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        list.add(frag);
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_fragmentos",15, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // lista_fragmentos ::= fragmento 
            {
              List<CompiledTexto> RESULT =null;
		int fragleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int fragright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledTexto frag = (CompiledTexto)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        List<CompiledTexto> list = new ArrayList<>();
                        list.add(frag);
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_fragmentos",15, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // lista_fragmentos ::= lista_fragmentos error 
            {
              List<CompiledTexto> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<CompiledTexto> list = (List<CompiledTexto>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_fragmentos",15, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // fragmento ::= TEXTO_PLANO 
            {
              CompiledTexto RESULT =null;
		int textoleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int textoright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		String texto = (String)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        RESULT = new CompiledCadena(texto);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("fragmento",16, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // fragmento ::= EMOJI_SMILE 
            {
              CompiledTexto RESULT =null;
		
                        RESULT = new CompiledEmoji(TipoEmoji.SMILE);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("fragmento",16, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // fragmento ::= EMOJI_SAD 
            {
              CompiledTexto RESULT =null;
		
                        RESULT = new CompiledEmoji(TipoEmoji.SAD);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("fragmento",16, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // fragmento ::= EMOJI_SERIOUS 
            {
              CompiledTexto RESULT =null;
		
                        RESULT = new CompiledEmoji(TipoEmoji.SERIOUS);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("fragmento",16, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // fragmento ::= EMOJI_HEART 
            {
              CompiledTexto RESULT =null;
		
                        RESULT = new CompiledEmoji(TipoEmoji.HEART);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("fragmento",16, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // fragmento ::= EMOJI_STAR 
            {
              CompiledTexto RESULT =null;
		
                        RESULT = new CompiledEmoji(TipoEmoji.STAR);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("fragmento",16, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // fragmento ::= EMOJI_MULTI_STAR 
            {
              CompiledTexto RESULT =null;
		int emojileft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int emojiright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		String emoji = (String)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        RESULT = new CompiledEmoji(TipoEmoji.MULTI_STAR,emoji);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("fragmento",16, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // fragmento ::= EMOJI_CAT 
            {
              CompiledTexto RESULT =null;
		
                        RESULT = new CompiledEmoji(TipoEmoji.CAT);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("fragmento",16, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserCompiled$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserCompiled$do_action(
    int                        CUP$ParserCompiled$act_num,
    java_cup.runtime.lr_parser CUP$ParserCompiled$parser,
    java.util.Stack            CUP$ParserCompiled$stack,
    int                        CUP$ParserCompiled$top)
    throws java.lang.Exception
    {
              return CUP$ParserCompiled$do_action_part00000000(
                               CUP$ParserCompiled$act_num,
                               CUP$ParserCompiled$parser,
                               CUP$ParserCompiled$stack,
                               CUP$ParserCompiled$top);
    }
}

}
