
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.pablocompany.proyectono1_compi1.compiler.logic.fuente;

import java_cup.runtime.*;
import java.util.*;
import com.pablocompany.proyectono1_compi1.compiler.models.errores.ErrorAnalisis;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.*;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.compiledlayouts.*;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.compiledforms.compiledquests.*;
import com.pablocompany.proyectono1_compi1.compiler.backend.modelos.formulariorecursos.compiledforms.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserCompiled extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SymCompiled.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserCompiled() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserCompiled(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserCompiled(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\026\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\006\020\000\002\006\017\000\002\012\004\000" +
    "\002\012\003\000\002\013\011\000\002\014\004\000\002" +
    "\014\003\000\002\015\011\000\002\005\003\000\002\005" +
    "\003\000\002\005\003\000\002\005\003\000\002\016\011" +
    "\000\002\017\004\000\002\017\003\000\002\020\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\103\000\004\034\006\001\002\000\006\002\000\034" +
    "\006\001\002\000\004\002\104\001\002\000\004\022\012" +
    "\001\002\000\006\002\ufffc\034\ufffc\001\002\000\006\002" +
    "\ufffe\034\ufffe\001\002\000\006\002\ufffd\034\ufffd\001\002" +
    "\000\004\035\013\001\002\000\004\034\015\001\002\000" +
    "\004\034\072\001\002\000\006\011\017\012\016\001\002" +
    "\000\004\035\034\001\002\000\004\035\020\001\002\000" +
    "\004\034\023\001\002\000\006\033\031\034\023\001\002" +
    "\000\006\033\uffed\034\uffed\001\002\000\004\013\024\001" +
    "\002\000\004\035\025\001\002\000\004\056\026\001\002" +
    "\000\004\035\027\001\002\000\006\033\uffec\034\uffec\001" +
    "\002\000\006\033\uffee\034\uffee\001\002\000\004\011\032" +
    "\001\002\000\004\035\033\001\002\000\004\034\uffef\001" +
    "\002\000\004\034\036\001\002\000\006\033\063\034\036" +
    "\001\002\000\004\024\040\001\002\000\006\033\ufff8\034" +
    "\ufff8\001\002\000\004\035\041\001\002\000\004\034\044" +
    "\001\002\000\006\033\057\034\044\001\002\000\006\033" +
    "\ufff5\034\ufff5\001\002\000\004\025\045\001\002\000\004" +
    "\035\046\001\002\000\004\034\006\001\002\000\004\033" +
    "\054\001\002\000\004\033\ufff1\001\002\000\004\033\ufff0" +
    "\001\002\000\004\033\ufff2\001\002\000\004\033\ufff3\001" +
    "\002\000\004\025\055\001\002\000\004\035\056\001\002" +
    "\000\006\033\ufff4\034\ufff4\001\002\000\004\024\061\001" +
    "\002\000\006\033\ufff6\034\ufff6\001\002\000\004\035\062" +
    "\001\002\000\006\033\ufff7\034\ufff7\001\002\000\004\012" +
    "\065\001\002\000\006\033\ufff9\034\ufff9\001\002\000\004" +
    "\035\066\001\002\000\004\033\067\001\002\000\004\022" +
    "\070\001\002\000\004\035\071\001\002\000\010\002\ufffa" +
    "\033\ufffa\034\ufffa\001\002\000\004\012\073\001\002\000" +
    "\004\035\074\001\002\000\004\034\036\001\002\000\006" +
    "\033\076\034\036\001\002\000\004\012\077\001\002\000" +
    "\004\035\100\001\002\000\004\033\101\001\002\000\004" +
    "\022\102\001\002\000\004\035\103\001\002\000\010\002" +
    "\ufffb\033\ufffb\034\ufffb\001\002\000\004\002\001\001\002" +
    "\000\006\002\uffff\034\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\103\000\014\002\004\003\003\004\007\006\010\007" +
    "\006\001\001\000\010\004\104\006\010\007\006\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\016\013\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\017\020\020\021" +
    "\001\001\000\004\020\027\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\012\034" +
    "\013\036\001\001\000\004\013\063\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\014\041" +
    "\015\042\001\001\000\004\015\057\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\005\046" +
    "\006\052\007\051\010\047\011\050\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\012\074\013\036\001\001\000\004" +
    "\013\063\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserCompiled$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserCompiled$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserCompiled$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




       LexerCompiled lex;
       private List<ErrorAnalisis> syntaxErrorListCompiled;

       // conexion de parser y lexer
       public ParserCompiled(LexerCompiled lex){
           super(lex);
           this.lex = lex;
           syntaxErrorListCompiled = new ArrayList<>();
       }

       // Getters
       public LexerCompiled getLexer(){
           return this.lex;
       }

       public List<ErrorAnalisis> getSyntaxErrorList(){
           return this.syntaxErrorListCompiled;
       }

        //Metodo que permite retornar los errores sintacticos del interprete
        public void syntax_error(Symbol simbolo) {
            List<Integer> ids = expected_token_ids();
            List<String> list = new ArrayList<>();

            if (ids.isEmpty()) {
                reportarErrorContextual(simbolo);
                return;
            }

            for (Integer id : ids) {
                list.add(traductor(symbl_name_from_id(id)));
            }

            String esperado = String.join(", ", list);
            String encontrado = (simbolo.value != null) ? simbolo.value.toString() : traductor(symbl_name_from_id(simbolo.sym));

            syntaxErrorListCompiled.add(new ErrorAnalisis(
                encontrado,
                "Sintactico",
                "Se esperaba: \"" + esperado + "\". Pero se encontro con: \"" + encontrado + "\"",
                simbolo.left,
                simbolo.right
            ));
        }

        public void unrecovered_syntax_error(Symbol simbolo) throws Exception {
            String encontrado = (simbolo.value != null) ? simbolo.value.toString() : traductor(symbl_name_from_id(simbolo.sym));
            syntaxErrorListCompiled.add(new ErrorAnalisis(
                encontrado,
                "Sintactico",
                "No se pudo recuperar el analisis cerca de: \"" + encontrado + "\".",
                simbolo.left,
                simbolo.right
            ));
        }

        private void reportarErrorContextual(Symbol simbolo) {

            String tokenEncontrado = (simbolo.value != null) ? simbolo.value.toString() : symbl_name_from_id(simbolo.sym);

            String mensaje = "Error de sintaxis cerca de \"" + tokenEncontrado + "\". ";

            if (tokenEncontrado.equals("TABLE") || tokenEncontrado.equals("SECTION")) {

                mensaje += "Asegurate de que la etiqueta este bien cerrada con \">\" o \"/>\".";

            } else if (tokenEncontrado.equals("IGUAL")) {

                mensaje += "Parece que faltan los parametros de layout (width, height, pointX, pointY).";

            } else {

                mensaje += "Revisa la estructura de las etiquetas anidadas.";

            }

            syntaxErrorListCompiled.add(new ErrorAnalisis(tokenEncontrado, "Sintactico", mensaje, simbolo.left, simbolo.right));
        }

        private String traductor(String nombre) {
            switch (nombre) {
                case "MENOR": return "\" < \"";
                case "MAYOR": return "\" > \"";
                case "IGUAL": return "\" = \"";
                case "DIAGONAL": return "\" / \"";
                case "CIERRE_ETIQUETA": return "\" /> \"";
                case "INICIO_ETIQUETA": return "\" </ \"";
                case "COMA": return "\" , \"";
                case "PARENT_APERTURA": return "\" ( \"";
                case "PARENT_CIERRE": return "\" ) \"";
                case "LLAVE_APERTURA": return "\" { \"";
                case "LLAVE_CIERRE": return "\" } \"";
                case "COLOR_HEX": return "un color hexadecimal (ej: #FFFFFF)";
                case "ENTERO": return "un valor numerico";
                case "TEXTO_PLANO": return "texto";
                case "TABLE": return "etiqueta <table>";
                case "SECTION": return "etiqueta <section>";
                case "LINE": return "etiqueta <line>";
                case "ELEMENT": return "etiqueta <element>";
                case "EOF": return "Final del documento";
                default: return nombre.toLowerCase().replace("_", " ");
            }
        }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserCompiled$actions {
  private final ParserCompiled parser;

  /** Constructor */
  CUP$ParserCompiled$actions(ParserCompiled parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserCompiled$do_action_part00000000(
    int                        CUP$ParserCompiled$act_num,
    java_cup.runtime.lr_parser CUP$ParserCompiled$parser,
    java.util.Stack            CUP$ParserCompiled$stack,
    int                        CUP$ParserCompiled$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserCompiled$result;

      /* select the action based on the action number */
      switch (CUP$ParserCompiled$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= compilado EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		CodigoInterpretado start_val = (CodigoInterpretado)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		RESULT = start_val;
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserCompiled$parser.done_parsing();
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // compilado ::= cuerpo_etiquetas 
            {
              CodigoInterpretado RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		List<CompiledForm> list = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        RESULT = new CodigoInterpretado(list);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("compilado",0, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // cuerpo_etiquetas ::= cuerpo_etiquetas etiqueta_principal 
            {
              List<CompiledForm> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<CompiledForm> list = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledContenedor e = (CompiledContenedor)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            list.add(e);
                            RESULT = list;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("cuerpo_etiquetas",1, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // cuerpo_etiquetas ::= etiqueta_principal 
            {
              List<CompiledForm> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledContenedor e = (CompiledContenedor)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            List<CompiledForm> list = new ArrayList<>();
                            list.add(e);
                            RESULT = list;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("cuerpo_etiquetas",1, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // etiqueta_principal ::= etiqueta_tabla 
            {
              CompiledContenedor RESULT =null;
		int tablaleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int tablaright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledTable tabla = (CompiledTable)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = tabla;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta_principal",2, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // etiqueta_principal ::= etiqueta_section 
            {
              CompiledContenedor RESULT =null;
		int secleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int secright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledSection sec = (CompiledSection)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = sec;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta_principal",2, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // etiqueta_tabla ::= MENOR TABLE MAYOR bloque_estilos MENOR CONTENT MAYOR filas_tabla INICIO_ETIQUETA CONTENT MAYOR INICIO_ETIQUETA TABLE MAYOR 
            {
              CompiledTable RESULT =null;
		int estilosleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-10)).left;
		int estilosright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-10)).right;
		CompiledEstilos estilos = (CompiledEstilos)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-10)).value;
		int filasleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)).left;
		int filasright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)).right;
		List<List<CompiledForm>> filas = (List<List<CompiledForm>>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)).value;
		
                        RESULT = new CompiledTable(-1, -1, 0, 0, filas, estilos);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta_tabla",4, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-13)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // etiqueta_tabla ::= MENOR TABLE MAYOR MENOR CONTENT MAYOR filas_tabla INICIO_ETIQUETA CONTENT MAYOR INICIO_ETIQUETA TABLE MAYOR 
            {
              CompiledTable RESULT =null;
		int filasleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)).left;
		int filasright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)).right;
		List<List<CompiledForm>> filas = (List<List<CompiledForm>>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)).value;
		
                        RESULT = new CompiledTable(-1, -1, 0, 0, filas, null);
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta_tabla",4, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-12)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // filas_tabla ::= filas_tabla fila 
            {
              List<List<CompiledForm>> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<List<CompiledForm>> list = (List<List<CompiledForm>>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		List<CompiledForm> f = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        list.add(f);
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("filas_tabla",8, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // filas_tabla ::= fila 
            {
              List<List<CompiledForm>> RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		List<CompiledForm> f = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        List<List<CompiledForm>> list = new ArrayList<>();
                        list.add(f);
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("filas_tabla",8, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // fila ::= MENOR LINE MAYOR celdas_tabla INICIO_ETIQUETA LINE MAYOR 
            {
              List<CompiledForm> RESULT =null;
		int filleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).left;
		int filright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).right;
		List<CompiledForm> fil = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).value;
		
                        RESULT = fil;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("fila",9, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // celdas_tabla ::= celdas_tabla celda 
            {
              List<CompiledForm> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		List<CompiledForm> list = (List<CompiledForm>)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledForm c = (CompiledForm)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        list.add(c);
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("celdas_tabla",10, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // celdas_tabla ::= celda 
            {
              List<CompiledForm> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledForm c = (CompiledForm)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                        List<CompiledForm> list = new ArrayList<>();
                        list.add(c);
                        RESULT = list;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("celdas_tabla",10, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // celda ::= MENOR ELEMENT MAYOR etiqueta INICIO_ETIQUETA ELEMENT MAYOR 
            {
              CompiledForm RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).right;
		CompiledForm e = (CompiledForm)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).value;
		
                        RESULT = e;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("celda",11, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // etiqueta ::= etiqueta_tabla 
            {
              CompiledForm RESULT =null;
		int tablaleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int tablaright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledTable tabla = (CompiledTable)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = tabla;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta",3, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // etiqueta ::= etiqueta_section 
            {
              CompiledForm RESULT =null;
		int secleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int secright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledSection sec = (CompiledSection)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = sec;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta",3, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // etiqueta ::= etiqueta_text 
            {
              CompiledForm RESULT =null;
		int textoleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int textoright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledText texto = (CompiledText)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = texto;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta",3, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // etiqueta ::= etiqueta_preguntas 
            {
              CompiledForm RESULT =null;
		int preguntasleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int preguntasright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		CompiledQuestions preguntas = (CompiledQuestions)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = preguntas;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("etiqueta",3, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // bloque_estilos ::= MENOR STYLE MAYOR lista_propiedades INICIO_ETIQUETA STYLE MAYOR 
            {
              CompiledEstilos RESULT =null;
		int estilosleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).left;
		int estilosright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).right;
		CompiledEstilos estilos = (CompiledEstilos)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-3)).value;
		
                        RESULT = estilos;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("bloque_estilos",12, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // lista_propiedades ::= lista_propiedades propiedad 
            {
              CompiledEstilos RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		CompiledEstilos list = (CompiledEstilos)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		int propleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int propright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		String prop = (String)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            RESULT = list;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_propiedades",13, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // lista_propiedades ::= propiedad 
            {
              CompiledEstilos RESULT =null;
		int propleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).left;
		int propright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()).right;
		String prop = (String)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.peek()).value;
		
                            CompiledEstilos est = new CompiledEstilos();

                            RESULT = est;
                        
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("lista_propiedades",13, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // propiedad ::= MENOR COLOR_KEY MAYOR COLOR_HEX MAYOR 
            {
              String RESULT =null;
		int hexleft = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).left;
		int hexright = ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).right;
		String hex = (String)((java_cup.runtime.Symbol) CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-1)).value;
		
                        RESULT = hex;
                    
              CUP$ParserCompiled$result = parser.getSymbolFactory().newSymbol("propiedad",14, ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.elementAt(CUP$ParserCompiled$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCompiled$stack.peek()), RESULT);
            }
          return CUP$ParserCompiled$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserCompiled$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserCompiled$do_action(
    int                        CUP$ParserCompiled$act_num,
    java_cup.runtime.lr_parser CUP$ParserCompiled$parser,
    java.util.Stack            CUP$ParserCompiled$stack,
    int                        CUP$ParserCompiled$top)
    throws java.lang.Exception
    {
              return CUP$ParserCompiled$do_action_part00000000(
                               CUP$ParserCompiled$act_num,
                               CUP$ParserCompiled$parser,
                               CUP$ParserCompiled$stack,
                               CUP$ParserCompiled$top);
    }
}

}
