// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: LexerFormsConfig.jflex

/********************** paquetes y otros ***********************/
package com.pablocompany.proyectono1_compi1.compiler.logic;

/*P*/

import java_cup.runtime.*;
import java.util.*;

/*Mis imports*/
import com.pablocompany.proyectono1_compi1.compiler.models.errores.ErrorAnalisis;


@SuppressWarnings("fallthrough")
public class LexerForms implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\2\u1f00\1\u2000\6\u1f00\1\u2100\1\u2200\1\u2300"+
    "\1\u2400\1\u2500\1\u2600\1\u2700\1\u2800\1\u1f00\31\u0100\1\u2900"+
    "\121\u0100\1\u2a00\4\u0100\1\u2b00\1\u0100\1\u2c00\1\u2d00\1\u2e00"+
    "\1\u2f00\1\u3000\1\u3100\53\u0100\1\u3200\10\u3300\31\u3400\1\u0100"+
    "\1\u3500\1\u3600\1\u0100\1\u3700\1\u3800\1\u3900\1\u3a00\1\u3b00"+
    "\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u0100\1\u4000\1\u4100\1\u4200"+
    "\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900\1\u4a00"+
    "\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u5000\1\u5100\1\u5200"+
    "\1\u5300\1\u3400\1\u5400\1\u5500\1\u5600\1\u5700\3\u0100\1\u5800"+
    "\1\u5900\1\u5a00\11\u3400\1\u5b00\4\u0100\1\u5c00\17\u3400\2\u0100"+
    "\1\u5d00\41\u3400\2\u0100\1\u5e00\1\u5f00\2\u3400\1\u6000\1\u6100"+
    "\27\u0100\1\u6200\2\u0100\1\u6300\1\u6400\1\u6500\1\u6600\41\u3400"+
    "\1\u6700\1\u0100\1\u6800\1\u6900\11\u3400\1\u6a00\22\u3400\1\u6b00"+
    "\1\u6c00\1\u6d00\1\u6e00\1\u6f00\1\u7000\1\u7100\1\u7200\1\u7300"+
    "\2\u1f00\1\u7400\4\u3400\1\u7500\1\u7600\1\u7700\1\u7800\1\u3400"+
    "\1\u7900\2\u3400\1\u7a00\1\u7b00\1\u7c00\2\u3400\1\u7d00\1\u7e00"+
    "\1\u7f00\1\u3400\1\u8000\1\u8100\1\u8200\3\u1f00\1\u8300\1\u8400"+
    "\1\u8500\1\u8600\1\u8700\1\u8800\4\u3400\246\u0100\1\u8900\20\u0100"+
    "\1\u8a00\1\u8b00\25\u0100\1\u8c00\34\u0100\1\u8d00\14\u3400\2\u0100"+
    "\1\u8e00\5\u3400\23\u6400\1\u8f00\17\u6400\1\u9000\u0adc\u3400\1\u9100"+
    "\1\u9200\u02fe\u3400";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\16\0\4\6"+
    "\1\1\3\7\1\10\11\7\1\11\1\7\12\12\7\7"+
    "\32\10\4\7\1\10\1\7\32\10\4\7\6\0\1\13"+
    "\32\0\2\7\4\10\4\7\1\10\2\7\1\0\7\7"+
    "\1\10\4\7\1\10\5\7\27\10\1\7\37\10\1\7"+
    "\u01ca\10\4\7\14\10\16\7\5\10\7\7\1\10\1\7"+
    "\1\10\21\7\160\14\5\10\1\7\2\10\2\6\4\10"+
    "\1\7\1\10\4\6\2\7\1\10\1\7\3\10\1\6"+
    "\1\10\1\6\24\10\1\6\123\10\1\7\213\10\1\7"+
    "\5\14\2\7\246\10\1\6\46\10\2\6\1\10\6\7"+
    "\51\10\2\7\2\6\2\7\1\10\1\6\55\14\1\7"+
    "\1\14\1\7\2\14\1\7\2\14\1\7\1\14\10\6"+
    "\33\10\4\6\4\10\2\7\13\6\6\0\5\7\1\10"+
    "\4\7\13\14\1\7\1\0\1\6\2\7\53\10\37\14"+
    "\4\7\2\10\1\14\143\10\1\7\1\10\7\14\1\0"+
    "\1\7\6\14\2\10\2\14\1\7\4\14\2\10\12\14"+
    "\3\10\2\7\1\10\16\7\1\6\1\0\1\10\1\14"+
    "\36\10\33\14\2\6\131\10\13\14\1\10\16\6\12\14"+
    "\41\10\11\14\2\10\4\7\1\10\2\6\1\14\30\10"+
    "\4\14\1\10\11\14\1\10\3\14\1\10\5\14\2\6"+
    "\17\7\1\6\31\10\3\14\2\6\1\7\1\6\13\10"+
    "\5\6\30\15\1\6\6\15\1\6\2\0\6\6\10\0"+
    "\25\10\1\15\10\10\14\15\11\0\17\14\1\0\41\14"+
    "\66\10\3\14\1\10\22\14\1\10\7\14\12\10\2\14"+
    "\2\7\12\14\1\7\20\10\3\14\1\6\10\10\2\6"+
    "\2\10\2\6\26\10\1\6\7\10\1\6\1\10\3\6"+
    "\4\10\2\6\1\14\1\10\7\14\2\6\2\14\2\6"+
    "\3\14\1\10\10\6\1\14\4\6\2\10\1\6\3\10"+
    "\2\14\2\6\12\14\4\10\7\7\2\10\1\7\1\14"+
    "\2\6\3\14\1\6\6\10\4\6\2\10\2\6\26\10"+
    "\1\6\7\10\1\6\2\10\1\6\2\10\1\6\2\10"+
    "\2\6\1\14\1\6\5\14\4\6\2\14\2\6\3\14"+
    "\3\6\1\14\7\6\4\10\1\6\1\10\7\6\14\14"+
    "\3\10\1\14\1\7\12\6\3\14\1\6\11\10\1\6"+
    "\3\10\1\6\26\10\1\6\7\10\1\6\2\10\1\6"+
    "\5\10\2\6\1\14\1\10\10\14\1\6\3\14\1\6"+
    "\3\14\2\6\1\10\17\6\2\10\2\14\2\6\12\14"+
    "\1\7\1\10\7\6\1\10\6\14\1\6\3\14\1\6"+
    "\10\10\2\6\2\10\2\6\26\10\1\6\7\10\1\6"+
    "\2\10\1\6\5\10\2\6\1\14\1\10\7\14\2\6"+
    "\2\14\2\6\3\14\7\6\1\0\2\14\4\6\2\10"+
    "\1\6\3\10\2\14\2\6\12\14\1\7\1\10\6\7"+
    "\12\6\1\14\1\10\1\6\6\10\3\6\3\10\1\6"+
    "\4\10\3\6\2\10\1\6\1\10\1\6\2\10\3\6"+
    "\2\10\3\6\3\10\3\6\14\10\4\6\5\14\3\6"+
    "\3\14\1\6\4\14\2\6\1\10\6\6\1\14\16\6"+
    "\12\14\11\7\1\10\1\7\5\6\5\14\10\10\1\6"+
    "\3\10\1\6\27\10\1\6\20\10\2\6\1\0\1\10"+
    "\7\14\1\6\3\14\1\6\4\14\7\6\2\14\1\6"+
    "\3\10\2\6\1\15\2\6\2\10\2\14\2\6\12\14"+
    "\7\6\11\7\1\10\3\14\1\7\10\10\1\6\3\10"+
    "\1\6\27\10\1\6\12\10\1\6\5\10\2\6\1\14"+
    "\1\10\7\14\1\6\3\14\1\6\4\14\7\6\2\14"+
    "\6\6\1\15\1\10\1\6\2\10\2\14\2\6\12\14"+
    "\1\6\2\10\1\0\14\6\4\14\1\15\10\10\1\6"+
    "\3\10\1\6\51\10\2\14\1\10\7\14\1\6\3\14"+
    "\1\6\4\14\1\10\1\7\4\6\3\10\1\14\7\7"+
    "\3\10\2\14\2\6\12\14\12\7\6\10\1\6\1\0"+
    "\2\14\1\6\22\10\3\6\30\10\1\6\11\10\1\6"+
    "\1\10\2\6\7\10\3\6\1\14\4\6\6\14\1\6"+
    "\1\14\1\6\10\14\6\6\12\14\2\6\2\14\1\7"+
    "\14\6\60\10\1\14\2\10\7\14\4\6\10\10\10\14"+
    "\1\7\12\14\2\7\45\6\2\10\1\6\1\10\1\6"+
    "\5\10\1\6\30\10\1\6\1\10\1\6\12\10\1\14"+
    "\2\10\11\14\1\10\2\6\5\10\1\6\1\10\1\6"+
    "\6\14\1\0\1\6\12\14\2\6\4\10\40\6\1\10"+
    "\27\7\2\14\6\7\12\14\13\7\1\14\1\7\1\14"+
    "\1\7\1\14\4\7\2\14\10\10\1\6\44\10\4\6"+
    "\24\14\1\7\2\14\5\10\13\14\1\6\44\14\1\6"+
    "\10\7\1\14\6\7\1\6\15\7\45\6\53\10\24\14"+
    "\1\10\12\14\6\7\6\10\4\14\4\10\3\14\1\10"+
    "\3\14\2\10\7\14\3\10\4\14\15\10\14\14\1\10"+
    "\17\14\2\7\46\10\1\6\1\10\5\6\1\10\2\6"+
    "\53\10\1\7\115\10\1\6\4\10\2\6\7\10\1\6"+
    "\1\10\1\6\4\10\2\6\51\10\1\6\4\10\2\6"+
    "\41\10\1\6\4\10\2\6\7\10\1\6\1\10\1\6"+
    "\4\10\2\6\17\10\1\6\71\10\1\6\4\10\2\6"+
    "\103\10\2\6\3\14\35\7\3\6\20\10\12\7\6\6"+
    "\126\10\2\6\6\10\2\6\1\7\u016c\10\2\7\21\10"+
    "\1\7\32\10\2\7\3\6\113\10\3\7\13\10\7\6"+
    "\15\10\1\15\4\10\3\14\1\0\11\6\1\15\22\10"+
    "\3\14\2\7\11\6\22\10\2\14\14\6\15\10\1\6"+
    "\3\10\1\6\2\14\14\6\64\10\40\14\3\7\1\10"+
    "\3\7\2\10\1\14\2\6\12\14\6\6\12\7\6\6"+
    "\13\7\3\14\2\0\12\14\6\6\131\10\7\6\5\10"+
    "\2\14\42\10\1\14\1\10\5\6\106\10\12\6\37\10"+
    "\1\6\14\14\4\6\14\14\4\6\1\7\3\6\2\7"+
    "\12\14\36\10\2\6\5\10\13\6\54\10\4\6\32\10"+
    "\6\6\12\14\1\7\3\6\42\7\27\10\5\14\2\6"+
    "\2\7\65\10\12\14\1\6\35\14\2\6\13\14\6\6"+
    "\12\14\6\6\7\7\1\10\6\7\2\6\16\14\1\7"+
    "\20\0\61\6\5\14\57\10\21\14\7\10\1\15\3\6"+
    "\12\14\21\7\11\14\11\7\3\6\3\14\36\10\15\14"+
    "\2\10\12\14\54\10\16\14\10\6\4\7\44\10\24\14"+
    "\3\6\5\7\12\14\3\6\3\10\12\14\44\10\2\7"+
    "\11\10\7\6\53\10\2\6\3\10\10\7\10\6\3\14"+
    "\1\7\25\14\4\10\1\14\6\10\1\14\2\10\3\14"+
    "\1\10\5\6\300\10\72\14\1\0\5\14\26\10\2\6"+
    "\6\10\2\6\46\10\2\6\6\10\2\6\10\10\1\6"+
    "\1\10\1\6\1\10\1\6\1\10\1\6\37\10\2\6"+
    "\65\10\1\6\7\10\1\7\1\10\3\7\3\10\1\6"+
    "\7\10\3\7\4\10\2\6\6\10\1\6\3\7\15\10"+
    "\3\7\2\6\3\10\1\6\7\10\2\7\1\6\13\7"+
    "\5\0\30\7\2\16\5\0\20\7\2\10\23\7\1\10"+
    "\13\7\5\0\1\6\12\0\1\7\1\10\2\6\13\7"+
    "\1\10\17\7\1\6\15\10\3\6\40\10\1\15\17\6"+
    "\15\14\4\7\1\14\3\7\14\14\17\6\2\7\1\10"+
    "\4\7\1\10\2\7\12\10\1\7\1\10\3\7\5\10"+
    "\6\7\1\10\1\7\1\10\1\7\1\10\1\7\4\10"+
    "\1\7\13\10\2\7\4\10\5\7\5\10\4\7\1\10"+
    "\21\7\51\10\3\7\4\6\u0197\7\31\6\13\7\25\6"+
    "\u0114\7\2\6\40\7\2\6\150\7\57\10\1\15\57\10"+
    "\1\15\205\10\6\7\4\10\3\14\2\10\5\6\7\7"+
    "\46\10\1\6\1\10\5\6\1\10\2\6\70\10\7\6"+
    "\1\10\1\7\16\6\1\14\27\10\11\6\7\10\1\6"+
    "\7\10\1\6\7\10\1\6\7\10\1\6\7\10\1\6"+
    "\7\10\1\6\7\10\1\6\7\10\1\6\40\14\57\7"+
    "\1\10\40\7\60\6\32\7\1\6\131\7\14\6\326\7"+
    "\32\6\14\7\4\6\5\7\3\10\31\7\11\10\6\14"+
    "\1\7\5\10\2\7\5\10\3\7\1\6\126\10\2\6"+
    "\2\14\2\7\3\10\1\7\132\10\1\7\4\10\5\6"+
    "\53\10\1\6\136\10\1\6\20\7\33\10\5\15\44\7"+
    "\14\6\20\10\37\7\1\6\340\7\266\10\12\15\100\7"+
    "\360\10\20\15\215\10\3\6\67\7\11\6\56\10\2\7"+
    "\15\10\3\7\20\10\12\14\2\10\24\6\57\10\1\14"+
    "\4\7\12\14\1\7\37\10\2\14\120\10\2\14\6\7"+
    "\10\6\27\7\11\10\2\7\147\10\2\7\65\10\2\15"+
    "\5\10\4\15\5\6\2\15\1\6\1\15\1\6\5\15"+
    "\30\6\5\15\13\10\1\14\3\10\1\14\4\10\1\14"+
    "\27\10\5\14\4\7\1\0\3\6\10\7\1\10\1\7"+
    "\6\6\64\10\4\7\10\6\2\14\62\10\22\14\10\6"+
    "\2\7\12\14\6\6\22\14\6\10\3\7\1\10\1\7"+
    "\2\10\13\14\34\10\10\14\2\7\27\10\15\14\13\6"+
    "\1\7\35\10\3\6\4\14\57\10\16\14\15\7\1\6"+
    "\1\10\12\14\4\6\2\7\5\10\1\14\12\10\12\14"+
    "\5\10\1\6\51\10\16\14\11\6\3\10\1\14\10\10"+
    "\2\14\2\6\12\14\2\6\4\7\27\10\3\7\1\10"+
    "\3\14\62\10\1\14\1\10\3\14\2\10\2\14\5\10"+
    "\2\14\1\10\1\14\1\10\30\6\3\10\2\7\13\10"+
    "\5\14\2\7\3\10\2\14\12\6\6\10\2\6\6\10"+
    "\2\6\6\10\11\6\7\10\1\6\7\10\1\6\53\10"+
    "\1\7\14\10\2\15\6\6\163\10\10\14\1\7\2\14"+
    "\2\6\12\14\6\6\244\10\14\6\27\10\4\6\61\10"+
    "\4\6\u0100\16\u0100\6\156\10\2\6\152\10\46\6\7\10"+
    "\14\6\5\10\5\6\1\10\1\14\12\10\1\7\15\10"+
    "\1\6\5\10\1\6\1\10\1\6\2\10\1\6\2\10"+
    "\1\6\154\10\20\7\21\6\153\10\2\7\20\6\100\10"+
    "\2\6\66\10\50\6\15\10\1\7\2\6\20\14\12\7"+
    "\6\6\20\14\3\7\2\10\30\7\3\10\3\7\1\6"+
    "\23\7\1\6\1\7\1\10\2\7\4\6\5\10\1\6"+
    "\207\10\2\6\1\0\1\6\3\7\1\10\13\7\12\14"+
    "\7\7\32\10\4\7\1\10\1\7\32\10\13\7\131\10"+
    "\3\6\6\10\2\6\6\10\2\6\6\10\2\6\3\10"+
    "\3\6\2\10\3\7\2\10\1\6\7\7\12\6\3\0"+
    "\2\7\2\6\14\10\1\6\32\10\1\6\23\10\1\6"+
    "\2\10\1\6\17\10\2\6\16\10\42\6\173\10\5\6"+
    "\3\7\4\6\55\7\3\6\11\7\65\10\32\7\1\6"+
    "\14\7\4\6\1\7\57\6\55\7\1\14\202\6\35\10"+
    "\3\6\61\10\17\6\1\14\33\7\4\6\40\10\4\7"+
    "\11\6\36\10\5\6\46\10\5\14\5\6\36\10\1\6"+
    "\1\7\44\10\4\6\10\10\1\7\5\10\52\6\236\10"+
    "\2\6\12\14\6\6\44\10\4\6\44\10\4\6\50\10"+
    "\10\6\64\10\13\6\1\7\13\15\1\6\17\15\1\6"+
    "\7\15\1\6\2\15\1\6\13\15\1\6\17\15\1\6"+
    "\7\15\1\6\2\15\103\6\67\10\11\6\26\10\12\6"+
    "\10\10\30\6\6\15\1\6\52\15\1\6\11\15\105\6"+
    "\6\10\2\6\1\10\1\6\54\10\1\6\2\10\3\6"+
    "\1\10\2\6\27\10\1\6\11\7\27\10\11\7\37\10"+
    "\10\6\11\7\60\6\23\10\1\6\2\10\5\6\5\7"+
    "\26\10\6\7\3\6\1\7\32\10\5\6\1\7\100\6"+
    "\70\10\4\6\2\7\2\10\20\7\2\6\56\7\1\10"+
    "\3\14\1\6\2\14\5\6\4\14\4\10\1\6\3\10"+
    "\1\6\35\10\2\6\3\14\4\6\1\14\11\7\7\6"+
    "\11\7\7\6\35\10\3\7\35\10\3\7\40\6\10\10"+
    "\1\7\34\10\2\14\4\6\14\7\11\6\66\10\3\6"+
    "\7\7\26\10\2\6\10\7\23\10\5\6\10\7\22\10"+
    "\7\6\4\7\14\6\7\7\120\6\111\10\67\6\63\10"+
    "\15\6\63\10\7\6\6\7\44\10\4\14\10\6\12\14"+
    "\u0126\6\37\7\1\6\52\15\1\6\2\0\3\6\2\15"+
    "\113\6\3\0\35\10\12\7\1\10\10\6\26\10\13\14"+
    "\11\7\26\6\22\15\4\0\52\6\25\15\33\6\27\10"+
    "\11\6\3\14\65\10\17\14\7\7\4\6\24\7\12\14"+
    "\1\0\2\15\2\0\1\15\11\6\4\14\55\10\13\14"+
    "\2\7\1\0\4\7\1\0\12\6\1\0\2\6\31\10"+
    "\7\6\12\14\6\6\3\14\44\10\16\14\1\6\12\14"+
    "\4\7\1\10\2\14\1\15\10\6\43\10\1\14\2\7"+
    "\1\10\11\6\3\14\60\10\16\14\4\10\4\7\4\14"+
    "\1\7\2\0\12\14\1\10\1\7\1\10\3\7\1\6"+
    "\24\7\13\6\22\10\1\6\31\10\14\14\6\7\1\14"+
    "\2\15\1\0\76\6\7\10\1\6\1\10\1\6\4\10"+
    "\1\6\17\10\1\6\12\10\1\7\6\6\57\10\14\14"+
    "\5\6\12\14\6\6\4\14\1\6\10\10\2\6\2\10"+
    "\2\6\26\10\1\6\7\10\1\6\2\10\1\6\5\10"+
    "\1\6\2\14\1\10\7\14\2\6\2\14\2\6\3\14"+
    "\2\6\1\10\6\6\1\14\5\6\5\10\2\14\2\6"+
    "\7\14\3\6\5\14\213\6\65\10\22\14\4\10\5\7"+
    "\12\14\1\6\1\7\1\6\1\7\1\14\1\10\2\15"+
    "\36\6\60\10\24\14\2\10\1\7\1\10\10\6\12\14"+
    "\246\6\57\10\7\14\2\6\11\14\27\7\4\10\2\14"+
    "\42\6\60\10\21\14\3\7\1\10\13\6\12\14\6\6"+
    "\15\7\23\6\53\10\15\14\1\10\7\6\12\14\66\6"+
    "\33\10\2\6\17\14\4\6\12\14\6\7\7\15\271\6"+
    "\54\10\17\14\1\7\144\6\100\10\12\14\11\7\14\6"+
    "\1\10\7\15\2\6\1\15\2\6\10\15\1\6\2\15"+
    "\1\6\30\15\6\0\1\6\2\0\2\6\4\0\1\15"+
    "\1\0\1\15\2\0\14\6\12\0\106\6\10\10\2\6"+
    "\47\10\7\14\2\6\7\14\1\10\1\7\1\10\1\14"+
    "\33\6\1\10\12\14\50\10\7\14\1\10\4\14\10\7"+
    "\1\14\10\6\1\10\13\14\56\10\20\14\3\7\1\10"+
    "\5\7\15\6\20\15\71\10\7\6\11\10\1\6\45\10"+
    "\10\14\1\6\10\14\1\10\5\7\12\6\12\14\23\7"+
    "\3\6\2\7\36\10\2\6\26\14\1\6\16\14\111\6"+
    "\7\10\1\6\2\10\1\6\46\10\6\14\3\6\1\14"+
    "\1\6\2\14\1\6\7\14\1\10\1\14\10\6\12\14"+
    "\6\6\6\10\1\6\2\10\1\6\40\10\5\14\1\6"+
    "\2\14\1\6\5\14\1\10\7\6\12\14\u0136\6\23\10"+
    "\4\14\2\7\7\6\2\0\1\15\1\0\15\15\1\6"+
    "\42\15\7\0\3\6\5\0\15\6\12\0\126\6\1\15"+
    "\17\6\35\7\4\10\21\7\15\6\1\7\232\10\146\6"+
    "\157\10\1\6\5\7\13\6\304\10\u014c\6\141\15\17\6"+
    "\57\10\1\15\21\0\6\15\17\0\252\6\107\10\271\6"+
    "\71\10\7\6\37\10\1\6\12\14\4\6\2\7\117\15"+
    "\1\6\12\0\6\6\36\10\2\6\5\14\1\7\12\6"+
    "\60\10\7\14\11\7\4\10\2\7\12\6\12\14\1\6"+
    "\7\7\1\6\25\10\5\6\23\10\260\6\100\10\33\7"+
    "\145\6\113\10\4\6\1\14\1\10\67\14\7\6\4\14"+
    "\15\10\100\6\2\10\1\7\1\10\1\0\13\6\2\0"+
    "\16\6\370\10\10\6\363\10\u01e3\15\52\6\11\15\u01e7\6"+
    "\4\15\1\6\7\15\1\6\2\15\1\6\37\10\4\15"+
    "\17\6\1\15\35\6\3\10\2\6\1\15\16\6\4\10"+
    "\10\6\u018c\10\4\6\153\10\5\6\15\10\3\6\11\10"+
    "\7\6\12\10\2\6\1\7\2\14\1\7\4\0\134\6"+
    "\56\0\2\6\27\0\271\6\366\7\12\6\47\7\2\6"+
    "\74\7\5\14\3\7\6\14\10\0\10\14\2\7\7\14"+
    "\36\7\4\14\73\7\27\6\102\7\3\14\1\7\232\6"+
    "\24\7\14\6\127\7\11\6\31\7\207\6\125\10\1\6"+
    "\107\10\1\6\2\10\2\6\1\10\2\6\2\10\2\6"+
    "\4\10\1\6\14\10\1\6\1\10\1\6\7\10\1\6"+
    "\101\10\1\6\4\10\2\6\10\10\1\6\7\10\1\6"+
    "\34\10\1\6\4\10\1\6\5\10\1\6\1\10\3\6"+
    "\7\10\1\6\u0154\10\2\6\31\10\1\7\31\10\1\7"+
    "\37\10\1\7\31\10\1\7\37\10\1\7\31\10\1\7"+
    "\37\10\1\7\31\10\1\7\37\10\1\7\31\10\1\7"+
    "\10\10\2\6\151\14\4\7\62\14\10\7\1\14\16\7"+
    "\1\14\7\7\17\6\5\14\1\6\17\14\120\6\37\15"+
    "\6\6\6\15\325\6\7\14\1\6\21\14\2\6\7\14"+
    "\1\6\2\14\1\6\5\14\5\6\76\15\41\6\1\0"+
    "\160\6\55\10\3\6\7\14\7\10\2\6\12\14\4\6"+
    "\1\10\1\7\u0140\6\36\15\1\0\21\6\54\10\16\14"+
    "\5\6\1\10\320\6\34\15\16\0\346\6\7\15\1\6"+
    "\4\15\1\6\2\15\1\6\17\15\1\6\305\10\2\6"+
    "\11\7\7\14\51\6\104\10\7\14\1\10\4\6\12\14"+
    "\4\6\2\7\u0111\6\77\7\1\10\4\7\114\6\75\7"+
    "\302\6\4\10\1\6\33\10\1\6\2\10\1\6\1\10"+
    "\2\6\1\10\1\6\12\10\1\6\4\10\1\6\1\10"+
    "\1\6\1\10\6\6\1\10\4\6\1\10\1\6\1\10"+
    "\1\6\1\10\1\6\3\10\1\6\2\10\1\6\1\10"+
    "\2\6\1\10\1\6\1\10\1\6\1\10\1\6\1\10"+
    "\1\6\1\10\1\6\2\10\1\6\1\10\2\6\4\10"+
    "\1\6\7\10\1\6\4\10\1\6\4\10\1\6\1\10"+
    "\1\6\12\10\1\6\21\10\5\6\3\10\1\6\5\10"+
    "\1\6\21\10\64\6\2\7\16\6\54\7\4\6\144\7"+
    "\14\6\17\7\2\6\17\7\1\6\17\7\1\6\45\7"+
    "\12\6\15\7\3\6\135\7\3\6\75\7\71\6\35\7"+
    "\15\6\54\7\4\6\11\7\7\6\2\7\16\6\6\7"+
    "\232\6\326\7\12\6\15\7\3\6\13\7\5\6\164\7"+
    "\14\6\131\7\7\6\14\7\24\6\14\7\4\6\70\7"+
    "\10\6\12\7\6\6\50\7\10\6\36\7\122\6\14\7"+
    "\1\6\145\7\1\6\4\7\3\6\51\7\2\6\6\7"+
    "\3\6\35\7\2\6\207\7\14\6\16\7\2\6\4\7"+
    "\4\6\3\7\5\6\3\7\15\6\6\7\u015a\6\12\0"+
    "\6\6\327\10\11\15\40\6\65\10\5\15\6\6\336\10"+
    "\2\6\u0182\10\16\6\u0131\10\37\6\36\10\342\6\113\15"+
    "\5\6\u0160\15\121\6\1\0\36\6\140\0\200\6\360\14"+
    "\20\6";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[37632];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\1\1\3\1\4\1\5"+
    "\1\6\1\1\1\0\1\7";

  private static int [] zzUnpackAction() {
    int [] result = new int[13];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\17\0\36\0\55\0\36\0\55\0\74\0\36"+
    "\0\113\0\132\0\113\0\151\0\151";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[13];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\3\1\6\1\7\1\3\1\10"+
    "\1\11\1\10\1\12\1\3\1\10\1\13\1\0\2\10"+
    "\4\0\5\10\1\0\2\10\21\0\1\4\2\0\1\4"+
    "\14\0\1\5\14\0\1\11\7\0\1\11\1\0\4\11"+
    "\12\0\1\14\1\12\16\0\1\15\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[120];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\2\1\1\11\3\1\1\0"+
    "\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[13];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    /****************** Codigo de usuario (codigo java) ***********************/

    //StringBuilder para cadenas de texto
    private StringBuilder string;

 /*-----------------------------------------------
                   Codigo del lexer
             -------------------------------------------------*/

    private List<ErrorAnalisis> errorLexList;

    public List<ErrorAnalisis> getLexicalErrors(){
        return this.errorLexList;
    }

    private void reportError(String message, String text){
         errorLexList.add(new ErrorAnalisis(text,"Lexico",message,(yyline+1),(yycolumn+1)));
    }

    /*-------------------------- Codigo para el parser --------------------------------*/


     /*-----------------------------------------------
              Codigo para el parser
        -------------------------------------------------*/

    private Symbol symbol(int type, Object object){
        return new Symbol(type, yyline+1, yycolumn+1, object);
    }

    private Symbol symbol(int type){
        return new Symbol(type, yyline+1, yycolumn+1);
    }


    /*Created by Pablo*/


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerForms(java.io.Reader in) {
      /****************** codigo dentro del constructor ******************/
    errorLexList = new ArrayList<>();
    string = new StringBuilder();

    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* ignorar */
            }
          // fall through
          case 8: break;
          case 2:
            { return symbol(sym.WHITESPACE, yytext());
            }
          // fall through
          case 9: break;
          case 3:
            { return symbol(sym.NEWLINE, yytext());
            }
          // fall through
          case 10: break;
          case 4:
            { reportError("Simbolo no existe en el lenguaje", yytext());
                    return symbol(sym.ERROR, yytext());
            }
          // fall through
          case 11: break;
          case 5:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 12: break;
          case 6:
            { return symbol(sym.ENTERO, Integer.parseInt(yytext()));
            }
          // fall through
          case 13: break;
          case 7:
            { return symbol(sym.DECIMAL, Double.parseDouble(yytext()));
            }
          // fall through
          case 14: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
