
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.pablocompany.proyectono1_compi1.compiler.logic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID = 5;
  public static final int ERROR = 2;
  public static final int error = 1;
  public static final int WHITESPACE = 3;
  public static final int DECIMAL = 6;
  public static final int EOF = 0;
  public static final int ENTERO = 7;
  public static final int NEWLINE = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERROR",
  "WHITESPACE",
  "NEWLINE",
  "ID",
  "DECIMAL",
  "ENTERO"
  };
}

